tonic/src/transport/endpoint.rs
tonic/src/transport/server.rs
tonic/src/transport/service/connection.rs

Wraps and exposes h2 options from hyper.

feat(transport): Expose http/2 settings

---

tonic/src/macros.rs

As mentioned in issue #37; The docs for `include_proto!` do not describe how to handle the situation where the tonic-build output directory has been modified.
This PR aims to improve the documentation by providing alternative methods to include generated files from tonic-build.

chore(docs): Add documentation for modified tonic-build output directory

---

tonic/src/transport/service/tls.rs

Currently, using an RSA key - or indeed any text which is not a PEM-encoded PKCS8-format key with RusTLS panics with an index-out-of- range exception. There is a similar problem loading certificates as well as private keys.
This commit introduces two new types of `TlsError` which indicate problems with loading a certificate or private key:
- `CertificateParseError`, indicating that the certificate cannot be parsed.
- `PrivateKeyParseError`, indicating that the private key cannot be parsed.
Additionally, in the case that reading the private key as PKCS8 fails, we now try loading it as an RSA key before failing.
This is not necessarily a complete solution, since the `Server` builder calls unwrap on the resulting error (which still panics), but the reason is at least now clearer since the …

fix(transport): Attempt to load RSA private keys in rustls

---

tonic/src/codec/decode.rs
tonic/src/codec/encode.rs
tonic/src/codec/mod.rs
tonic/src/codec/prost.rs
tonic/src/codec/tests.rs

This is a naive fix for the buffer growing beyond capacity
and producing a panic. Ideally, we should do a better job
of not having to allocate for new messages by using
a link list.
Related to #32

fix(codec): Fix buffer decode panic on full

---

tonic-build/src/client.rs
tonic-build/src/lib.rs
tonic-build/src/server.rs
tonic-build/tests/protos/empty.proto
tonic-build/tests/protos/wellknown.proto
tonic-build/tests/wellknown.rs

This change introduces the ability to let `prost-build`
provide the fully qualified type path for types that
start with `google.protobuf`.

fix(codegen): Use wellknown types from `prost-types`

---

tonic/src/transport/server.rs

Prevents the server exiting after a bad TLS handshake / error during
accept(). Instead the connection is dropped and the server continues to
serve new clients.
Previously an error would bubble up from the TLS library (tested with
rustls) and would cause:
```rust
Server::builder()
.rustls_tls(Identity::from_pem(&cert, &key))
.clone()
.serve(config.bind_addr(), AnExampleServer::new(endpoint))
.await?;
```
to exit with:
```
[src/main.rs:85] &e = Error(
Server,
Error(
Accept,
Custom {
kind: InvalidData,
error: CorruptMessage,
},
),
)
```
This can be reproduced by dialling to a tonic server's socket and sending junk
until it crashes.
Unfortunately I'm a little unsure how to test this!

fix(transport): Avoid exit after bad TLS handshake

---

README.md

The example in the readme uses tonic-build, but it doesn't mention that you need a dependency on the tonic-build package so the build fails.
Adding the dependency to the readme should help new users.
Should the version be specified as 0.1.0-alpha.1? I still get errors with this revised code because Cargo downloads the 0.0.0 package for `*`. Should it be like the tonic-build example which just says to put a version and it should match between tonic and tonic-build?

add tonic-build to readme

---

README.md

Developers who are adding tonic to an existing project may not have the edition set. This will cause errors in the generated service code.
Explicitly specify the edition in the example to make the requirement clear.

Suggestion: Add edition to example Cargo.toml snippet

---

tonic/src/transport/server.rs

This naming error slipped in as part of #48 - in a `ServerTlsConfig` you should specify `ServerConfig` rather than a `ClientConfig` for `rustls`

fix(transport): Rename server tls config method

---

README.md

This swaps out the readme example to use instead a link to the
routeguide tutorial.

chore(readme): Remove readme examples

---

tonic-build/src/client.rs

Closes #94.
It's literally a single line edit, so might as just do it myself :smile: 
Fixes `generate_connect`'s method signature when the "transport" feature is disabled.

fix(build): Fix missing argument in generate_connect

---

.github/workflows/CI.yml

r? @taiki-e this crate is awesome :) 

chore: Add `cargo-hack` to check features

---

tonic-build/src/client.rs
tonic-examples/src/authentication/client.rs
tonic-examples/src/gcp/client.rs
tonic-examples/src/helloworld/client.rs
tonic-examples/src/multiplex/client.rs
tonic-examples/src/routeguide/client.rs
tonic-examples/src/tls/client.rs
tonic-examples/src/tls_client_auth/client.rs
tonic-interop/src/bin/client.rs
tonic/Cargo.toml
tonic/benches/benchmarks/compiled_protos/helloworld.rs
tonic/src/transport/channel.rs
tonic/src/transport/endpoint.rs
tonic/src/transport/mod.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/discover.rs
tonic/src/transport/service/mod.rs
tonic/src/transport/service/reconnect.rs

This makes it so you can check if the initial connection
is established. Before this we used reconnect which would
lazily attempt to connect. So if you were trying to connect
to a non existant Server you wouldn't find out until after
you attempted your first RPC. This simplifies everything
by allowing you connect before creating the RPC client.
BREAKING CHANGE: `Endpoint::channel` was removed in favor of
an async `Endpoint::connect`.

feat(transport): Change channel connect to be async

---

tonic-examples/helloworld-tutorial.md
tonic-examples/routeguide-tutorial.md

Both tutorials were missing `.await` on the client connect call, causing the compiler to issue errors.
Thanks for alce#6260 on the #tonic-users discord channel for providing the answer.
Add `.await?` to `let mut client = GreeterClient::connect("http://[::1]:50051")` in both tutorials

chore(tutorials): Add .await after client connect call

---

tonic-examples/routeguide-tutorial.md

This patch updates  the route-guide tutorial to work with latest release.

fix error in routeguide tutorial

---

tonic/src/transport/server.rs
tonic/src/transport/service/connector.rs

The combination of the Nagle algorithm on a client, and delayed ack on a server
can introduce up to 200ms latency if a small gRPC messages is sent with multiple
writes.
Enable TCP_NODELAY to make sure that neither client, nor server buffer their
messages for too long when exchaning small requests.

feat(transport): Enable TCP_NODELAY.

---

.github/workflows/CI.yml

This PR updates GitHub Actions to use stable Rust. It is complementary to #122 which updates the documentation around this.

Use Stable Rust in CI

---

tonic/Cargo.toml
tonic/src/lib.rs
tonic/src/transport/endpoint.rs
tonic/src/transport/service/tls.rs

As per #101, it is sometimes desirable to use standard web PKI roots for gRPC clients. This commit adds a method to `ClientTlsConfig` to allow this. The behaviour differs per TLS library:
- OpenSSL uses `openssl-probe` to search the system for roots and add them.
- ~Rustls adds the Mozilla-supplied roots from the `webpki-roots` crate.~
~This is not feature flagged, as there appears to be no convenient way to gate a dependency on multiple conditions.~

feat(transport): Add system root anchors for TLS

---

.github/workflows/CI.yml
tonic-interop/test.sh

Now that #125 has landed we should be able to add a Windows build of the interop tests without too many problems. It's not expected to pass the first time around.

Add Windows build for interop crate

---

.github/workflows/CI.yml
tonic-examples/Cargo.toml
tonic-interop/Cargo.toml
tonic-interop/src/bin/client.rs
tonic-interop/src/bin/server.rs
tonic-interop/test.sh

This PR adds feature flags to `tonic-interop` to allow selection of OpenSSL or Rustls in order to allow both to be tested in CI under a wide variety of situations. Various small-level changes are needed throughout the Cargo files and test scripts to accommodate this.

Allow selection of TLS library in Interop tests

---

.github/workflows/CI.yml

This clarifies what CI is doing, since the `Interop (Rustls)` crate does not have a matrix.

Clarify what the Interop (Rustls) task is doing during CI

---

tonic-examples/src/gcp/client.rs
tonic-examples/src/tls/client.rs
tonic-examples/src/tls/server.rs
tonic-examples/src/tls_client_auth/client.rs
tonic-examples/src/tls_client_auth/server.rs
tonic-interop/src/bin/client.rs
tonic-interop/src/bin/server.rs
tonic/src/transport/endpoint.rs
tonic/src/transport/server.rs

This patch changes builders to take self by value.
closes #115

fix(transport): Update builders to move self

---

.github/workflows/CI.yml
README.md
tonic-examples/Cargo.toml
tonic-interop/Cargo.toml
tonic-interop/src/bin/client.rs
tonic-interop/src/bin/server.rs
tonic-interop/test.sh
tonic/Cargo.toml
tonic/src/lib.rs
tonic/src/transport/endpoint.rs
tonic/src/transport/mod.rs
tonic/src/transport/server.rs
tonic/src/transport/service/tls.rs
tonic/src/transport/tls.rs

This pull request removes support for OpenSSL now that the interop tests can run using Rustls, as discussed in Discord.

fix(transport): Remove support for OpenSSL

---

tonic/src/status.rs

This patch adds shortcut constructors for all Status codes as well as documentation for all Code variants.
`From<tokio::timer::timeout::Elapsed>` for Status is also implemented, which is useful for the in-progress revamp of request timeouts.
Edit: the `From<Elapsed> for Status` does not compile when the transport feature is disabled. Without it, there is no tokio available. I removed the implementation for now.

feat: Add `Status` constructors

---

tonic/src/metadata/map.rs
tonic/src/request.rs
tonic/src/response.rs

Tonic's `MetadataMap` prevents  entries with  invalid or reserved HTTP2 header names to be inserted but does not disallow headers reserved by the gRPC protocol.
The metadata map is then copied verbatim to HTTP headers and written the wire. Some headers may be updated by inserting new values but some will be written as-is.
This patch prevents a small set of headers to be written when sending requests or responses. It does not panic or returns errors if entries with these names are added to the metadata map, it just won't copy them to http request or responses.

fix: Sanitize custom metadata

---

deny.toml

`crossbeam-queue` is currently brought in both by Rayon (up to date v0.2.0) and Hyper's dependency chain (0.1.x). Since Hyper is in the process of updating things, I proposed we temporarily allow this to pass CI and revisit it when there is a new release of Hyper or the relevant dependencies thereof.
This will fix the build of #151, #148 etc.

Temporarily allow duplicate crossbeam-queue crates

---

tonic/src/transport/endpoint.rs
tonic/src/transport/server.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/connector.rs

Long running tcp connections (grpc streaming), with very low activity may be silently disconnected if done though firewalls or NAT routers. TCP keepalive fixes this.
Expose hyper tcp_keepalive api on `Endpoint` and `Server`.

feat(transport): Expose tcp keepalive to clients & servers

---

tonic-examples/Cargo.toml
tonic/Cargo.toml
tonic/src/transport/endpoint.rs
tonic/src/transport/server.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/connector.rs

feat: expose tcp_nodelay for clients and servers

---

tonic-examples/Cargo.toml

tokio 0.2 split out its macros into [a feature that is disabled by default](https://docs.rs/tokio/0.2.3/tokio/attr.main.html), so we'll re-enable it to allow example builds to work once more.

chore(examples): enable the macros feature for tokio::main

---

tonic/src/transport/server.rs

Some error messages, one about hyper::server::Builder not existing and another about lack of clone on futures. Just putting this up as an initial WIP to make sure I'm on the right track :)
Recommended good practice for gRPC so should be exposed
Expose it via builder pattern

feat(transport): Add server graceful shutdown

---

examples/Cargo.toml
examples/src/uds/client.rs
examples/src/uds/server.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/connector.rs
tonic/src/transport/service/discover.rs
tonic/src/transport/service/io.rs
tonic/src/transport/service/tls.rs

feat(transport): Allow custom IO and UDS example

---

tonic-build/src/client.rs

fix(build): Remove async ready

---

tonic/src/transport/service/reconnect.rs

fix(transport): Fix lazily reconnecting

---

examples/src/gcp/client.rs
examples/src/tls/client.rs
examples/src/tls/server.rs
examples/src/tls_client_auth/client.rs
examples/src/tls_client_auth/server.rs
interop/src/bin/client.rs
interop/src/bin/server.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/channel/tls.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/server/tls.rs

fix(transport): Remove with_rustls for tls config

---

examples/src/routeguide/client.rs
examples/src/routeguide/server.rs
interop/src/client.rs
interop/src/server.rs
tests/included_service/src/lib.rs
tonic-build/src/client.rs
tonic-build/src/lib.rs
tonic-build/src/server.rs

`snake_case` service names for code generation. Uses a naive function but should be enough for most cases.
closes #182

fix(build): snake_case service names

---

tonic/src/transport/service/connector.rs

b90c340 (feat(transport): Allow custom IO and UDS example (#184),
2019-12-13) changed the Connector type to be more generic instead of
only allowing the HttpConnector type, during this change the
`Service::poll_ready` impl was changed from calling
`MakeConnection::poll_ready` on `self.http` to `self` resulting in
infinite recursion due to the blanket imple of
`MakeConnection::poll_ready` calling `Service::poll_ready`.
This fixes the bug by calling `MakeConnection::poll_ready` on
`self.inner` instead of `self`.
Fixes #191

fix(transport): Fix infinite recursion in `poll_ready`

---

examples/routeguide-tutorial.md

While following the [routeguide tutorial](https://github.com/hyperium/tonic/blob/master/examples/routeguide-tutorial.md) I found a few links from the #180 moves that need a refresh.
Links updated 😉 
---
Tonic is shaping up great. Thanks to you, project maintainers!

chore(docs): Fix routeguide tutorial source links

---

.github/workflows/CI.yml

This upgrades CI from manually downloading cargo-deny to use our new [cargo-deny GitHub Action](https://github.com/EmbarkStudios/cargo-deny-action). 
Includes a lot of fixes, upgrades a new features as it brings cargo-deny from 0.4.0 to 0.5.2. List of changes:
https://github.com/EmbarkStudios/cargo-deny/releases
Biggest one here is that it will now also check the RUSTSEC security advisory database and will (by default) fail builds if any security advisories are detected for used crates
I was thinking first that we should wait until we have a v1 of the action and cargo-deny before using it, but as `tonic` is one of the first non-Embark repos using `cargo-deny` I think we can switch to the action here - but monitor how it works. Can always pin the action to an exact version also and/or …

chore(ci): Switch to use GitHub Action for cargo-deny

---

examples/src/gcp/client.rs
examples/src/tls/client.rs
examples/src/tls/server.rs
examples/src/tls_client_auth/client.rs
examples/src/tls_client_auth/server.rs
tonic/src/lib.rs

I noticed that the examples link in docs.rs was broken.  This fixes that along with some of the examples.
https://docs.rs/tonic/0.1.0-beta.1/tonic/
Replace `tonic-examples` with just `examples`

Fix examples link

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/error.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs

Fixes #213 
Makes the `tonic::transport::Error` type much simpler. It just forwards what's in the source error now. It was previously opaque anyway so a user of the library could not match on the `ErrorKind` or anything like that anyway.
However, this just solves the problem of the error not having redundant information in it. The library still uses a lot of opaque `Box<dyn Error>` internally. I personally think it would be nicer if `tonic` exposed a proper `hyper::Error` where the error comes from `hyper` etc. But I did not feel that was in scope for getting this part done.

fix(transport): Improve `Error` type

---

examples/routeguide-tutorial.md

chore(example) Fix routeguide errors

---

tonic-build/src/lib.rs

Adds support for prost-build's "extern_path" feature. This allows you to
reference another prost-generated protobuf, including any traits that
may have been defined for it, from another crate or location.
When using protobuf definitions not only defined in, but also extended by, another crate - you need to use prost's `extern_path` feature, so that the generated code references your extended external definitions, rather than creating new ones.
Add `extern_path` to `tonic-build`.
There are no tests, as there were none to begin with. It does Work On My Machine, though.

feat(build): Add extern_path config support

---

examples/Cargo.toml
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
interop/Cargo.toml
tests/included_service/Cargo.toml
tests/same_name/Cargo.toml
tests/wellknown/Cargo.toml
tonic-build/Cargo.toml
tonic/Cargo.toml

This upgrades tonic to prost's master branch, and moves everything to
bytes 0.5.
Prost has lots of bug fixes and new features. Lets use them. 
Move to prost master, pending a (very soon) release of prost.

chore: Upgrade to prost master and bytes 0.5

---

deny.toml
examples/Cargo.toml
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
interop/Cargo.toml
interop/src/bin/client.rs
interop/src/bin/server.rs
tests/included_service/Cargo.toml
tests/same_name/Cargo.toml
tests/wellknown/Cargo.toml
tonic/Cargo.toml

Closes #123 and #93
This removes the required bytes dependency because of the upstream change https://github.com/danburkert/prost/pull/254.
This also updates the deny config, we no longer bring in two versions of `syn/quote/proc_macro2`. Currently, the only two left duplicate dependencies is `winapi 0.2/0.3`/`autocfg 0.1/1`.

chore: Remove required bytes dep and clean up deny

---

examples/Cargo.toml
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
interop/Cargo.toml
tests/included_service/Cargo.toml
tests/same_name/Cargo.toml
tests/wellknown/Cargo.toml
tonic-build/Cargo.toml
tonic/Cargo.toml

As far as I remember I think this was one of the last issues that tonic 0.1.0 is not yet released ?
Updated all occurences of prost, prost-build and prost-derive to the just released 0.6, replacing the git / master branch dependency.

chore: Upgrade to prost, prost-build and prost-derive 0.6 (#230)

---

Cargo.toml
examples/Cargo.toml
examples/src/authentication/client.rs
examples/src/authentication/server.rs
examples/src/gcp/client.rs
examples/src/interceptor/client.rs
examples/src/interceptor/server.rs
examples/src/uds/client.rs
interop/Cargo.toml
interop/src/bin/server.rs
interop/src/lib.rs
interop/src/server.rs
tonic-build/src/client.rs
tonic-build/src/server.rs
tonic/src/client/grpc.rs
tonic/src/interceptor.rs
tonic/src/lib.rs
tonic/src/request.rs
tonic/src/server/grpc.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/service/layer.rs
tonic/src/transport/service/mod.rs

This change introduces proper gRPC interceptors that are avilable
regardless of the transport used. Each codegen service now produces an
additional method called `with_interceptor` that accepts a
`Interceptor`.
All examples have been updated to use this new style and interop has a
custom `tower::Service` middleware to echo the headers. There is also a
new `interceptor` example that shows basic usage.

feat: Add gRPC interceptors

---

tonic-build/src/client.rs

Docstring for client modules incorrectly says "server"
Fix that!

fix(build): Typo with client mod docstring

---

tonic/src/transport/channel/tls.rs
tonic/src/transport/error.rs

fix(transport): Use Uri host if no domain for tls

---

examples/routeguide-tutorial.md
examples/src/routeguide/server.rs

Keep the example code simple.
1. Remove `pin_mut!` macro in the example code because `Streaming` is `Unpin` for any `T`.
2. Update the corresponding doc.
3. Change the return type to `Self::RouteChatStream`, it is already well defined above.

chore(docs): Remove unecessary pinning

---

tonic/Cargo.toml
tonic/src/status.rs

Many crates in the Rust ecosystem are now moving to `percent-encoding` 2.0, and it'd be great to have `tonic` stay up-to-date 
Upgrade `percent-encoding`. Because the API breaks with the new release, some minor changes are necessary to get the same behavior as before.

chore: upgrade `percent-encoding` 1.0.1 -> 2.0

---

Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/my_application/build.rs
tests/extern_path/my_application/src/main.rs
tests/extern_path/proto/my_application/service.proto
tests/extern_path/proto/uuid/uuid.proto
tests/extern_path/uuid/Cargo.toml
tests/extern_path/uuid/build.rs
tests/extern_path/uuid/src/lib.rs
tonic-build/src/lib.rs

tonic-build will replace all paths except for google well known types
with one rooted at the super module. For paths that have already been
replaced with a fully qualified path via the extern_path config option,
(e.g. "::uuid::Uuid"), this results in an invalid path
(e.g. "super::::uuid::Uuid"), and a build failure. These paths should
also be excluded when prefixing relative modules with super.
See commit message, and #260 
When extern_path'd are used in service method definitions, prost-build panics.
See https://github.com/cthulhua/tonic_extern_path/tree/master for a repro of the issue (it works when build against this branch).
Similar to how google well known types are handled, in the event an absolute path would be made relative, leave it absolute.

fix(build): Don't replace extern_paths

---

tonic-build/src/lib.rs

fix(build): Ignore non `.rs` files with rustfmt

---

examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
examples/src/helloworld/server_blocking.rs

Added a new blocking hello_world server example. 
Also corrected the way .proto file is compiled in the files https://github.com/hyperium/tonic/blob/master/examples/helloworld-tutorial.md and https://github.com/hyperium/tonic/blob/master/examples/routeguide-tutorial.md  
This is done in an attempt to close #253

chore: Add blocknig server example

---

tonic/src/lib.rs

This is small typo fix on the name of the `rustls` library.

chore: typo ruslts -> rustls

---

tonic/src/metadata/encoding.rs
tonic/src/metadata/key.rs
tonic/src/metadata/value.rs

Rust 1.42 deprecates the `description()` method of `std::error::Error` and provides a blanket implementation suggesting implementation of `std::fmt::Display` instead. We already implemented `Display` for error types but in terms of the deprecated `description`. This commit implements `Display` directly and falls back to the blanket implementation of `description()`.

Remove use of std::error::Error.description()

---

tonic-build/src/server.rs

This commit adjusts the code generation for the internal structs in the implementation of `Service<http::Request<HyperBody>>` for `*Server<T>` in order to annotate internal structs whose names are derived from gRPC method names with `[allow(non_camel_case_types)]`. This supresses compiler warnings about type names when compiling generated code. The struct names are not exposed externally, so this has no impact on types seen by library consumers.
Fixes #295.

Allow non_camel_case_types on some codegen structs

---

tonic-build/src/lib.rs

Remove unnecessary println! from tonic-build:
`out: Output { status: ExitStatus(ExitStatus(0)), stdout: "", stderr: "" }`
can get a bit noisy and I think it serves no purpose.
Also, fixed a couple of typos, sorry to mix things up but such small edits...hope you don't mind.

fix(build): Remove debug println!

---

tonic-build/src/server.rs
tonic/src/codegen.rs

close #281 
I choose to use `BoxBody`as a generic body when the transport feature is disabled. Let me know if it's a good choice.

fix(build): Server service uses generic body bound

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/service/connection.rs

Expose HTTP2 keep alive support as provided by hyper.
Motivated by https://github.com/hyperium/tonic/issues/258
Add's the config options to the `Endpoint` struct and passes them along to hyper when building a connection.

feat(transport): Expose http2 keep-alive support

---

tonic/src/status.rs

Changes are just a Copy pasta of [this pr](https://github.com/tower-rs/tower-grpc/pull/191) in tower-rs.
Reference #292 for motivation. 
The prescribed solution exposes two constructors with `Status::with_details` and `Status::with_raw_details` that allow the caller to construct a Status with a `Code`, `String`, and `Bytes` or a `Message` to be converted into bytes.

feat: Add Status with Details Constructor

---

tonic-build/src/client.rs

fix(build): Derive Debug for public structs

---

tonic-build/src/prost.rs

feat(build): Add support for custom prost config

---

examples/src/blocking/client.rs

Drop order in blocking example is actually the opposite of what the comment mentions
Switch the order. According to https://github.com/rust-lang/rfcs/blob/master/text/1857-stabilize-drop-order.md#tuples-structs-and-enum-variants Rust structs drop their fields in decl order (unlike C++ which is I imagine what tripped things up here). I just learned this recently myself!

chore: Update blocking example drop order

---

Cargo.toml
tests/ambiguous_methods/Cargo.toml
tests/ambiguous_methods/build.rs
tests/ambiguous_methods/proto/ambiguous_methods.proto
tests/ambiguous_methods/src/main.rs
tonic-build/src/server.rs

I have an existing proto with a method that was unfortunately named `Drop`, and the tonic stub did not compile. When calling methods on Arc<MyService> where the method is also defined on `Arc` (e.g. `drop` and `clone`), calling `inner.#method_ident(request)` will actually attempt to call the `Arc` method instead of the method on the service, resulting in a compile error when building the generated rust file. 
Here is an excerpt from a test proto, which I have added as [tests/ambiguous_methods/proto/ambiguous_methods.proto](https://github.com/hyperium/tonic/pull/327/files#diff-208d3daf20d818dcfca5ffc390bfb0ee):
```proto
service HelloService {
rpc Drop (DropReq) returns (DropResp);
rpc Clone (DropReq) returns (DropResp);
}
```
This change removes the ambiguity by dereferencing the inner …

fix(build): Remove ambiguity in service method call

---

tonic/src/transport/tls.rs

Currently there is no way to examine certificates obtained by peer_certs functions
Introduced functions enable consumer to parse and examine provided DER certificates

feat(transport): Add AsRef impl for Certificate

---

examples/Cargo.toml
examples/README.md
examples/src/autoreload/server.rs

I was trying to figure out whether the trick actix-web uses for [autoreloading](https://actix.rs/docs/autoreload/) the server would work with tonic. All that was needed was to add [listenfd](https://crates.io/crates/listenfd) as a dependency, install [systemfd](https://crates.io/crates/systemfd), change the following code:
```rust
Server::builder()
.add_service(GreeterServer::new(greeter))
.serve(addr)
.await?;
```
to:
```rust
let server = Server::builder()
.add_service(GreeterServer::new(greeter));
match listenfd::ListenFd::from_env().take_tcp_listener(0)? {
Some(listener) => {
let mut listener = tokio::net::TcpListener::from_std(listener)?;
server.serve_with_incoming(listener.incoming()).await?;
}
None => {
server.serve(addr).await?;
}
}
```
and run:
```sh
systemfd --no-pid -s …
```

chore(example): Autoreloading server example

---

.github/workflows/CI.yml

[v1 release notes](https://github.com/EmbarkStudios/cargo-deny-action/releases/tag/v1.0.0)
Only changes from cargo-deny 0.6.4 -> 0.6.6 so should just work

chore: Upgrade cargo-deny-action v0 -> v1

---

tonic/src/transport/service/discover.rs

Trying my luck with a PR for this, even though I'm a newbie here.
Please provide feedback and correct me if I'm wrong.
fixes #334
Apply optional tls-connector to the discovery client if the tls-feature is enabled.
Performed some tests combined with this patch: https://github.com/johanot/etcd-rs/commit/ad8a2649447877fbe8b8252355963871039a75ee on etcd-rs - since etcd-rs uses the balanced_list service endpoint to connect to etcd. It seemed to work just fine using TLS.

fix(transport): Apply tls-connector for discovery when applicable (#334)

---

tonic/src/client/mod.rs

Help users better discover cloning the client is the simple way to use it concurrently
Relates to https://github.com/hyperium/tonic/issues/285
Expand on `client` module docs
I considered added docstrings to the generated client implementations, but it was gonna take me a little bit to grok that and I don't have a ton of extra time right now unfortunately. Plus, the generated stuff rarely works in IDE doc help anyway. Putting it in the module docs should make it more discoverable.
Hope this helps! Thanks!

Add some info about concurrent usage to client mod

---

tests/integration_tests/tests/status.rs
tonic/src/status.rs

Issue #343 as well as some Discord discussions around May 5th—7th 2020 contain motivation for the PR. 
- Added `metadata` field to the `Status` struct, like in the `Response` struct
- If the provided metadata contains any headers with names reserved either by the gRPC spec or by `Status` fields (e.g. `grpc-status-details-bin`), they will be ignored.
- Updated existing `Status` constructors and conversions to support `metadata`
- Added `Status` constructors with `metadata` only or also with `details`
- Updated `Debug` and `Display` implementations for `Status` to support the new field
- Added an integration test for the functionality
- This change should be backward compatible

feat: Add metadata to error responses

---

examples/helloworld-tutorial.md

Fixed wrong path "proto/helloworld.proto" for `compile_protos` first argument. `build.rs` being in the project root, means the correct path should be "src/proto/helloworld.proto".

chore: wrong path for call to `compile_protos`

---

examples/helloworld-tutorial.md

This change reverts #366. The `proto/` directory, as described in the guide, is created under the root of the crate. Not under `src/`.
I've also included a fix to the `grpcurl` endpoint.

chore(docs): fix incorrect proto path in helloworld tutorial

---

examples/Cargo.toml
examples/src/hyper_warp/server.rs
tonic/Cargo.toml
tonic/src/transport/service/reconnect.rs

pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*

fix: Remove uses of pin_project::project attribute

---

tonic/src/transport/channel/endpoint.rs

This PR adds a new method `get_uri` for `Endpoint`, to allow user to get the `&Uri` from an `Endpoint`
I am using `tonic` and stored the `Endpoint`, ensure I can reconnect GRPC server directly, however sometimes I need to get the uri in `Endpoint` to print some log.
One way is to create a wrapper `struct Endpoint(Uri, tonic::transport::Endpoint)`, but it will allocate a new `Uri`.
I think the better way is let `Endpoint` can return the `Uri` reference which is in the `Endpoint`, user can use it to print logs or do something else, without unnecessary allocating.
related issue is #370

feat: add new method get_uri for Endpoint

---

examples/Cargo.toml
examples/README.md
examples/src/tower/server.rs

Note that this also adds `impl From<Status> for http::Response<BoxBody>`
in order to make writing middleware which can return an error much
easier.
This is based off the example from https://gist.github.com/LucioFranco/9d5cab419797f54fc7b96bc409d8c6e8. It has been expanded into something a little more complex which requires specifying the Request/Response types but allows for intercepting metadata values with an async context. This allows lookups to happen to verify things like auth tokens.
Most of the code here is the example, but it also replaces `Grpc::map_status` with an `impl From<Status> for http::Response<tonic::body::BoxBody>` in order to make it easier to write middleware which can return an error.

Add tower server example

---

tonic/src/server/grpc.rs
tonic/src/status.rs

In experimenting for #375, I noticed that there's not a convenient way for converting a `Status` into an `http::Response` for use in tower Services. This moves the private implementation to `Status::to_http` as originally discussed in Discord.
For the most part `server::Grpc::map_status` was just renamed to `Status::to_http`. Almost no code was changed.

Add to_http method for Status

---

tonic-build/src/client.rs
tonic-build/src/server.rs

If prost allows for no packages then tonic generates bad endpoints for both clients and servers. See https://github.com/hyperium/tonic/issues/381.
The solution is to make the `.` between the package name and service name dependent on whether or not the package is empty.

Allow empty packages - fixes #381

---

examples/src/gcp/client.rs
examples/src/tls/client.rs
examples/src/tls/server.rs
examples/src/tls_client_auth/client.rs
examples/src/tls_client_auth/server.rs
interop/src/bin/client.rs
interop/src/bin/server.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs

We ran into `tls_connector` failing and causing our app to panic and shutdown as it seems there wasn't any way to avoid panicking in `tls_config`.
So after talking to @LucioFranco briefly `tls_config` now returns a `Result` instead and propagates errors to the caller, where they have to be handled. 
This is a bit of an intrusive change to the API here. could alternatively introduce an additional `tls_config` function that does the error handling and keep the existing unwrapping one, to allow it to become an additive opt-in minor semver change instead?

Propagate errors in tls_config instead of unwrap/panic

---

examples/routeguide-tutorial.md

Since we already define the type we can just use it instead of writing it again
The example on the bidirectional streaming is confusing since we are casting the output 
of `Box::pin()` to a type. However it is the same type as the associated type `RouteChatStream`.
It makes the code more clean and understandable.
Use the associated type instead of writing the type again.

Make the cast in Bidirectional stream smaller

---

tonic/src/codec/decode.rs

It is not a bug-fix or a new feature as such. Just being more explicit and loud in reporting error using the communication direction. 
We encountered this error message today:
```rust
(Status { code: Internal, message: "Unexpected compression flag: 123" }
```
It's not immediately obvious as to whether this error-scenario was encountered while _sending_ the request or while _receiving_ the response. I think adding that information in the message would be highly helpful to figure out the actual source causing the error. 
It's pretty simple. I used `self.direction` to detect the error-scenario (as in, sending or receiving?) and created an error message accordingly.
Please let me know if this little improvement is acceptable in this form, or I missed out anything important. I'd like to make …

Use direction in error reporting during decode

---

tonic/src/status.rs

Resolves #383 
This PR adds `Display` impl for `Code`. 
Additionally, it adds `description` method to get Code description as static string.

Implement Display for Code

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/discover.rs
tonic/src/transport/service/reconnect.rs

Adds a 'lazy' constructor which will not attempt to connect to the
endpoint until first use. This is useful in situations where the
connection is created when the remote service may temporarily not be
responding, such as server startup.
Fixes #167

Add Endpoint::connect_lazy method

---

examples/Cargo.toml
examples/src/optional/server.rs
tonic/src/transport/server/mod.rs

https://github.com/hyperium/tonic/issues/265
This is currently an incomplete solution - it is the minimum required to demonstrate this approach and allow for a decision.
It mirrors closely the way `optional_layer` method works.
* Is this zero-cost?
* Should `NamedService` be implemented on `Either` like this? Does this break anything?
* There's an `Unimplemented` service which seems to do the same thing as `EmptyService`, perhaps we should use that instead?
After deciding whether this approach is feasible the following needs to be done:

Add optional service methods

---

tonic/Cargo.toml

I've been debugging some issues with tls-roots not working properly on macOS, so I figured I'd bump packages to the latest versions just in case something was fixed there.
I used cargo-outdated to check for the latest versions and updated them.

Bump packages to latest versions

---

deny.toml

chore: Ignore `ansi_term` in `deny.toml`

---

tests/integration_tests/tests/connection.rs
tonic/src/transport/service/reconnect.rs

Before this fix, if the connect phase of the transport failed before
ever establishing a connection, we would never return the error until
the first call to send a request. This PR changes that behavior to only
forward the error to the call method if we have ever made a connection
before. If we have never established a connection before then
`Reconnect` will return an error on the call to `poll_ready`.
Fixes #403

fix(transport): Return connection error on `Channel::connect`

---

tonic/src/transport/channel/endpoint.rs

I was trying to understand a project that uses tonic and it was hard to understand exactly what connect_with_connector  (especially since you need to provide a bogus URL to use it). It wasn't until I landed on https://github.com/hyperium/tonic/pull/184 that I understood what was going on. I think the documentation is lacking a bit of context for that function.
Added a bit of context to that function's documentation

doc(transport): improve connect_with_connector doc

---

tonic-build/src/server.rs

According to the spec content-type should be set. Related to https://github.com/hyperium/tonic/pull/434
Add the application/grpc content-type header.

fix(build): Add content-type for generated unimplemented service

---

interop/src/server.rs
interop/test.sh

Fixes https://github.com/hyperium/tonic/issues/414.
As part of the fix, two interop test cases `go client -> rust server` were added. I will include the rest once https://github.com/hyperium/tonic/pull/440 gets merged.

fix(interop) fix failing interop test with go client

---

tonic-build/src/lib.rs

For `prost`, on NixOS, it is better to explicitly define Protobuf related
environment variables `PROTOC` and `PROTOC_INCLUDE`.
On NixOS, `prost` will require explicit setting of environment variables 
- `PROTOC` 
- `PROTOC_INCLUDE`
Documentation instructions are added in `tonic-build` crate per request of @LucioFranco.

tonic-build: (docs) adds NixOS related hints

---

tonic/src/transport/channel/tls.rs

Both my test and function 'tls_connector' indicated 'domain_name' works for using `rustls_client_config` or not

fix(transport): Fix wrong doc for domain

---

tests/integration_tests/tests/connection.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/reconnect.rs

Channels created with lazy connections never try to reconnect if the first connection attempt fails. This is because `Reconnect` returns `Poll::Ready(Err)` on `poll_ready` and the service is considered dead.
This change passes a flag to Reconnect to signal if the connection is intended to be lazy, in which case reconnect returns the error on the next call. A new `Connection::lazy` constructor is provided to avoid threading booleans around.
fixes #452

fix(transport): reconnect lazy connections after first failure

---

tests/integration_tests/tests/user_agent.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/error.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/mod.rs
tonic/src/transport/service/user_agent.rs

This PR adds a  user-agent header to client requests. The default value is `tonic/x.x.x`. The value can be configured through the `Channel` builder.
```rust
Endpoint::from_static("...").user_agent("Greeter 1.1")?.connect();
```
The value passed to the `user_agent` method will be prepended to the default, in this case the full value will be: `Greeter 1.1 tonic/0.3.1`.
The header is added by a new `UserAgent` layer in the client's service stack. While this is not the most straight forward implementation, it seemed to be the cleanest and safest one. It also aligns better with other client implementations (grpc-go clients, in particular).
**Alternatives**
* Remove `user-agent` from the list of grpc reserved headers.
* Do not filter out the `user-agent` header in tonic <-> http request …

feat(transport): add user-agent header to client requests.

---

tonic-build/src/server.rs

I submitted a pr earlier that made it so that when prost supports protobufs without a package spec that tonic will already support it. Because prost doesn't actually support the feature I can't see a way to test the functionality. I just tried spinning up a server and had an issue with the implementation of the `NamedService` trait in hyper where it wasn't respecting the package spec. This is a fix for that.
If the package is empty then don't add a preceding `.` to the namespace.

fix(build): Match namespace code with other generated packages

---

tonic/src/metadata/encoding.rs
tonic/src/metadata/key.rs
tonic/src/metadata/value.rs

Fixes clippy lint warnings in metadata module.
Note that this PR manually implements `Hash` for `MatadataValue`.  This was necessary because there is a manual `PartialEq` implementation. This is particularly important for binary metadata values.

chore: fix warnings in metadata module

---

tonic/src/transport/service/discover.rs

If the first connection to the endpoint in an `Insert` changeset fails, the service goes into a failed state and the channel is dropped:
```
[2020-11-17T19:49:49.555562881+00:00] DEBUG: test/19660 on luca-XPS-15-9570: connecting to 127.0.0.124:5000
[2020-11-17T19:49:49.555756890+00:00] DEBUG: test/19660 on luca-XPS-15-9570: updating from discover
[2020-11-17T19:49:49.555879512+00:00] DEBUG: test/19660 on luca-XPS-15-9570: service failed
error: load balancer discovery error: error trying to connect: tcp connect error: Connection refused (os error 111)
```
This is not coherent with the behavior we observe if the connection is broken after having successfully connected at least once - the channel remains open and we try to reconnect without disrupting calls.
The current PR makes the …

feat(transport): Connect lazily in the load balanced channel

---

tonic/src/client/grpc.rs

The C++ gRPC server sometimes returns both headers and trailers. An
excerpt from Wireshark:
```
Stream: HEADERS, Stream ID: 1, Length 136, 200 OK
Header: :status: 200 OK
Header: x-middleware: expected value
Header: content-type: application/grpc
Header: grpc-accept-encoding: identity,deflate,gzip
Header: accept-encoding: identity,gzip
Stream: HEADERS, Stream ID: 1, Length 92
Header: grpc-status: 2
Header: grpc-message: Unknown
Header: x-arrow-status: 9
Header: x-arrow-status-message-bin: VW5rbm93bg
```
Before this commit, only the metadata from the trailer would be
available, missing the `x-middleware` header:
```
MetadataMap {
headers: {
"x-arrow-status-message-bin": "VW5rbm93bg",
"x-arrow-status": "9",
},
}
```
Merge the metadata before returning the error

Merge trailer and inital headers into status on err

---

tonic/src/transport/server/mod.rs

Adds two methods to `transport::server::Server` for setting HTTP2 server
keepalive interval and timeout as exposed by `hyper::server::Builder`.
Fixes #474
**Note**: I have not included a test, since this feature uses a functionality exposed and tested by [hyper](https://docs.rs/hyper/0.13.8/hyper/server/struct.Builder.html#method.http2_keep_alive_interval).
The details behind the motivation and proposed solution can be found in the issue #474

feat(transport): expose HTTP2 server keepalive interval and timeout

---

examples/Cargo.toml
examples/src/timeout/client.rs
examples/src/timeout/server.rs
examples/src/tower/client.rs
tonic/src/transport/channel/mod.rs

Fixes #481. Adds `Service` impl for `Channel`.
This PR replaces `GrpcService` impl for `tonic::transport::Channel` with `Service` impl. The two trait implementations cannot co-exist due to name conflict, but the former impl will be still alive thanks to the [general trait implementation for `Service` implementors](https://github.com/hyperium/tonic/blob/90858926b6a788f78f9c7bbdd7dda127f7f41e2c/tonic/src/client/service.rs#L33-L51).
**Notes**:
After applying this change, _existing codes that both imports `GrpcService` and `Service` traits can be broken_ due to multiple method definitions. This can be easily fixed by removing an import whichever or calling the preferable method explicitly. In this crate, only `examples/src/tower/client.rs` will be affected, so I fixed that in the second …

transport: impl Service for Channel instead of GrpcService

---

examples/routeguide-tutorial.md

The URL to the Async Trait section of the Rust Async Book needed updating.
Update the URL.

fixes routeguide tutorial URL to async book

---

tonic/Cargo.toml
tonic/src/status.rs

Solves #394 
Adds `h2` as a dependency and feature gate under `transport`

Enable `h2` errors

---

tonic/src/transport/service/tls.rs

Prevent problems reading individual certs from the cert store from interfering with the use of other valid certs when the `tls-roots` feature is enabled.
Fixes #519 
MacOS users will often have certs in their Trusted Settings Record that cannot be parsed by `rustls_native_roots` (used in conjunction with the `tls-roots` feature here). This change makes `tls-roots` usable for those users again.
Similar to [this implementation in `hyper-rustls`](https://github.com/ctz/hyper-rustls/blob/master/src/connector.rs#L34), one-off errors are effectively ignored when loading the native cert store.

Gracefully handle bad native certs

---

examples/src/tls_client_auth/server.rs
tonic/Cargo.toml
tonic/src/transport/server/conn.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/service/tls.rs

feat(transport): Fix TLS accept w/ peer certs

---

tonic/src/transport/server/mod.rs

Exposes option to configure the max http2 frame size used by the
underlying hyper server via the `tonic::transport::Server` builder.
Refs: #264
Refs #264 
Add as optional parameter to the `tonic::transport::Server` builder to be passed to the hyper server builder.

tonic: add max http2 frame size to server.

---

tonic/src/transport/service/reconnect.rs

fix(transport): return Poll::ready until error is consumed 

---

examples/helloworld-tutorial.md

I got a error when trying to run helloworld tutorial
```
thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'
```
because tonic 0.4 currently depends on Tokio 1.x.
updated example to use Tokio 1.x.

Fix helloworld tutorial.

---

tonic/Cargo.toml

In tower 0.4.0 we missed a couple of re-exports that tonic 0.4.0 depends
on. So tonic really depends on tower at least version 0.4.1. Since
specifying your tower depedency as 0.4 means you might get 0.4.0, you
might get build errors when updating tonic. Such as [#553] and [#552].
This fixes that by bumping tonic's dependency on tower to 0.4.4. That
means users will get at least tower version 0.4.4, but semver compatible
updates are still allowed.
Fixes https://github.com/hyperium/tonic/issues/553
[#553]: https://github.com/hyperium/tonic/issues/553
[#552]: https://github.com/hyperium/tonic/issues/552

fix: Depend on at least tower 0.4.4

---

tonic-build/src/client.rs
tonic-build/src/prost.rs
tonic-build/src/server.rs

In a project where we don't want to modify prost for empty packages, we need to implement SPIRE workload api which does not use a GRPC package.
This PR adds a `disable_package_emission` option to `tonic-build` that will not emit a prost-provided package on GRPC endpoints. This allows the protofile to include a package declaration to satisfy prost, and be protocol-compatible with a service expecting no package.

feat(build): Add disable_package_emission option to tonic-build

---

tonic/src/transport/channel/endpoint.rs

This is particularly handy when combined with `clap::value_t`.
Here's demo of it working with Clap:
```bash
cargo +stable init --bin tonic-demo
cd tonic-demo
cat <<-EOF >> Cargo.toml
clap = "*"
tonic = { path = "../hyperium/tonic/tonic" }
EOF
cat <<-EOF > src/main.rs
use clap::{value_t, App, Arg};
use tonic::transport::Endpoint;
fn main() {
let matches = App::new("tonic-demo")
.arg(Arg::with_name("host"))
.get_matches();
let x = value_t!(matches.value_of("host"), Endpoint);
println!("{:?}", x);
}
EOF
cargo +stable run -- https://127.0.0.1:443
```
Add a `impl FromStr for Endpoint`. It clones since the `s`'s lifetime is too short otherwise.

chore: add FromStr for Endpoint

---

Cargo.toml
examples/Cargo.toml
examples/README.md
examples/build.rs
examples/src/reflection/server.rs
tonic-build/src/prost.rs
tonic-reflection/Cargo.toml
tonic-reflection/build.rs
tonic-reflection/proto/reflection.proto
tonic-reflection/src/lib.rs
tonic-reflection/src/server.rs
tonic-reflection/tests/proto/grpc.reflection.v1alpha.rs
tonic-reflection/tests/proto/mod.rs
tonic-reflection/tests/server.rs
tonic/src/macros.rs

Issue #165 describes the motivations for the gRPC Reflection Service, along with the upstream [definition](https://github.com/grpc/grpc/blob/master/doc/server-reflection.md).
This pull request implements a new crate, `tonic-reflection` which implements the gRPC Reflection Service and provides a builder for registering protocol buffer `FileDescriptorProto`s. In the first instance, this relies on danburkert/prost#311, or a similar method, to embed encoded versions of the descriptor in code.
This is an early work in progress, and only implements the `ListServices` and `FileContainingSymbol` aspects of the reflection API, though this is enough to interrogate the shape of services and messages using `grpcurl`. The new example server can be used with `grpcurl` to verify this:
```console
$ …
```

feat: Implement gRPC Reflection Service

---

tonic-build/src/lib.rs

The Rust Bazel rules ([rules_rust](https://github.com/bazelbuild/rules_rust)) is looking to add some tools for building targets with Tonic. In development of https://github.com/bazelbuild/rules_rust/pull/479 it was found that `tonic-build` calls `rustfmt` and expects this to be in the user's PATH. This is generally not going to be the case when Building in Bazel. We're looking for a way to specify this binary without needing to rely on or modify PATH.
Cargo already has a [pattern for specifying environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads) to control what binaries are used during builds. The change here adopts the same functionality as Cargo and allows for an environment variable (`RUSTFMT`) to optionally …

feat(build): Use `RUSTFMT` to find `rustfmt` binary

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-reflection/Cargo.toml
tonic/Cargo.toml
tonic/src/lib.rs

Superseds https://github.com/hyperium/tonic/pull/563

Prepare `0.4.1` release

---

tonic/src/codec/prost.rs

I was curious how one would go about writing a custom Tonic Codec. While looking at the MockEncoder and MockDecoder I came across this issue: https://github.com/hyperium/tonic/issues/583
The configures the Prost tests module, fixes the imports, and reading the decode buffer.

Fix Prost codec tests and cfg

---

Cargo.toml
tests/stream_conflict/Cargo.toml
tests/stream_conflict/build.rs
tests/stream_conflict/proto/stream_conflict.proto
tests/stream_conflict/src/main.rs
tonic-build/src/server.rs
tonic/src/codegen.rs

I've encountered some proto files for upstream services which have a Service named 'Stream'. The generated trait for the service then conflicts with the futures_core trait.
This PR fixes this by not exporting `Stream` in tonic/codegen.rs, and instead refer to the trait using `futures_core::Stream` when generating code. There's a new test named 'stream_conflict' added to catch regressions.
Closes #588.

Use fully qualified path for futures_core::Stream in codegen

---

tonic-reflection/src/server.rs

Hello, I fixed a one-character typo in a docstring.
Thank you for all your great work :slightly_smiling_face:.

Fix docstring typo

---

examples/routeguide-tutorial.md
examples/src/routeguide/server.rs

I followed [routeguide-tutorial.md](https://github.com/hyperium/tonic/blob/master/examples/routeguide-tutorial.md) but there's a problem with ListFeaturesStream at compile time.
Luckily I found a [solution](https://github.com/hyperium/tonic/issues/540#issuecomment-771739578) in one of the issues.
This PR is to adopt what is suggested in the comment above both in `routeguide-tutorial.md` and `server.rs`.

Fix ListFeaturesStream return type on RouteGuide Tutorial

---

tonic/src/transport/channel/mod.rs

This seems to be confused about plural vs singular (and gets the plural form wrong). I think plural is more appropriate since `Endpoint::connect()` and `Endpoint::connect_lazy()` only take a `&self`.

Improve comment on Channel::builder()

---

tonic/src/status.rs

I have a `tower::Service` that generates time-series metrics for gRPC RPCs. That code currently has reimplementations of `Status::from_header_map` and `Code::from_bytes` to extract the gRPC status from a `hyper::http::Response`. I would rather not reimplement those functions.
Export `Status::from_header_map` and `Code::from_bytes` from the crate.

feat: Expose status constructors

---

tonic/src/codec/decode.rs

During profiling for bottlenecks in my tonic powered message queue, I noticed that a large amount of compute was spent in reallocating and `memmov`ing over read buffers. 
This PR gets rid of the reallocs entirely by pre-allocating the buffer for the entire message body directly after the message size is known instead of only reserving space for the next chunk when they come in.
In my testing with 8MiB messages, this improved throughput from 370MiB/s to 560MiB/s, which is roughly a 50% improvement. I originally mistyped the numbers, thus the "30-40%" in the commit message -- didn't want to force-push just for that.

fix(codec): Allocate inbound buffer once

---

tonic/src/metadata/map.rs

We have some gRPC servers in Java which requires callers to it set deadline. Currently seems it is not possible to use tonic as a client to talk to those servers as we cannot set `grpc-timeout` on the header?
As it also mentioned and others would like to remove this as well in PR https://github.com/hyperium/tonic/pull/516, also related to this discussion https://github.com/hyperium/tonic/issues/75.
Not sure when can https://github.com/hyperium/tonic/pull/516 be shipped in but this change could perhaps go in first as it blocks not me (see https://github.com/hyperium/tonic/issues/75#issuecomment-772143514)
Remove `grpc-timeout` from the reserved list.
Otherwise please let me know how to set `deadline` on the call from tonic as a client.

Remove grpc-timeout header from reserved headers

---

tonic-health/build.rs
tonic-health/proto/health.proto
tonic-health/src/lib.rs

Resolves https://github.com/hyperium/tonic/issues/471
It can be hard to test the health check server without the client and the proto module. By exposing this, we make it easier for users to do so.
Making the proto module public for `health.proto` and flipping build_client to true in `build.rs`

feat(health): Expose proto and client (#471)

---

tonic/src/transport/service/connector.rs

This pr enables automatic tls configuration for clients, when certain conditions are met. It enables clients to connect to a tls server without explicitly creating a `ClientTlsConfig` struct and a `Channel`:
```rust
let mut client = GreeterClient::connect("https://example.com").await?;
// client is now usable
```
For the connector to attempt to add a default tls configuration:
* the `tls-roots` feature must be enabled
* the url passed to `connect` must have the https scheme
* the url passed to `connect` must have a valid domain name (ips are not supported)
* if the client is created with an explicit channel, the channel must not have tls configured.
If any of these conditions is not met,  then the behavior should be exactly as before.
There is some additional work needed to improve errors …

feat(tonic): Configure tls automatically when possible

---

tonic-build/src/lib.rs
tonic-health/src/lib.rs
tonic-reflection/src/lib.rs
tonic-types/src/lib.rs
tonic/src/lib.rs
tonic/src/macros.rs

I noticed this was missing while working on something else.

chore: Add `deny(broken_intra_doc_links)` to all crates

---

tonic/src/metadata/map.rs
tonic/src/metadata/mod.rs
tonic/src/request.rs

This will set the `grpc-timeout` to a value formatted according to [the spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md).

feat(tonic): Add `Request::set_timeout`

---

CHANGELOG.md
tonic/Cargo.toml
tonic/src/lib.rs

* **client:** Add `Request::set_timeout` ([#615](https://github.com/hyperium/tonic/issues/615)) ([dae31d0](https://github.com/hyperium/tonic/commit/dae31d0))
* **transport:** Configure TLS automatically when possible ([#445](https://github.com/hyperium/tonic/issues/445)) ([b04c1c6](https://github.com/hyperium/tonic/commit/b04c1c6))
* **transport:** Support timeouts with the `grpc-timeout` header ([#606](https://github.com/hyperium/tonic/issues/606)) ([9ff4f7b](https://github.com/hyperium/tonic/commit/9ff4f7b))

chore: Prepare tonic `0.4.3`

---

examples/src/health/README.md
tonic-health/README.md

I didn't know how to run health checks for a tonic server. As per https://github.com/hyperium/tonic/issues/471, the client for the health service is not exposed.
This example is an easy way I found to run the checks. Other users may benefit from it 
See the script added

add healthcheck example

---

examples/src/tower/client.rs
examples/src/tower/server.rs

Doing
```rust
let clone = self.inner.clone();
Box::pin(async move {
let response = clone.call(request).await?;
Ok(response)
})
```
If `self.inner` is (or contains) a `tower::buffer::Buffer` might panic.
That is because [cloning a `Buffer` drops the permit](https://github.com/tower-rs/tower/blob/master/tower/src/buffer/service.rs#L169-L183) that was acquired in
`poll_ready`, meaning it is no longer ready and panic in `call`.
The solution is to use `mem::replace` to take the ready service and pass
that into the async block.
Fixes https://github.com/hyperium/tonic/issues/545

fix(examples): Fix tower examples

---

tonic/src/status.rs

`Code` is already trivial to convert into an `i32` however that isn't
immediately obvious by looking at the docs. This has tripped me up
before.
Implementing `From<Code>` for `i32` should hopefully make it a bit more
obvious.

feat(tonic): implement `From<Code>` for `i32`

---

tonic/src/metadata/map.rs

Removes manual `Send` and `Sync` impls for these types as they weren't
necessary:
- `metadata::Iter`
- `metadata::IterMut`
- `metadata::ValueDrain`
- `metadata::ValueIterMut`
Since all the types they contained were `Send + Sync` we can rely on the
compiler automatically adding the impls.
Also added some tests to ensure we don't accidentally make them `!Send`
or `!Sync` in the future.
Fixes https://github.com/hyperium/tonic/issues/636

feat(metadata): remove manual `Send + Sync` impls for metadata types

---

tonic/src/status.rs

**Note:** This is a breaking change.
I agree with
https://github.com/hyperium/tonic/issues/384#issuecomment-652653446 its
probably fine to remove `Code::__NonExhaustive` and require users to do
an exhaustive match. Seems unlikely that new error codes will be added.
Fixes https://github.com/hyperium/tonic/issues/384

feat(tonic): remove `Code::__NonExhaustive`

---

tonic/src/transport/server/mod.rs

Previously `Server::trace_fn` would receive `&HeaderMap` which meant you
couldn't add things like the URI to the span.
With this change it now receives `&http::Request<()>`. It doesn't
receive the body since that requires an additional generic parameter
which spreads to a lot of places. There also isn't much you can do with
the body of a borrowed `http::Request` anyways so its probably fine.
Fixes https://github.com/hyperium/tonic/issues/630

feat(tonic): pass `trace_fn` the request rather than just the headers

---

tonic/src/transport/server/mod.rs

Should save some allocations. Didn't actually benchmark it.

fix(transport): remove needless `BoxFuture`

---

examples/src/interceptor/server.rs
tests/integration_tests/Cargo.toml
tests/integration_tests/tests/extensions.rs
tonic/src/client/grpc.rs
tonic/src/extensions.rs
tonic/src/lib.rs
tonic/src/request.rs
tonic/src/response.rs

Adds `tonic::Extensions` which is a newtype around `http::Extensions`.
Request extensions can be set by interceptors with
`Request::extensions_mut` and retrieved from RPCs with
`Request::extensions`. Extensions can also be set in tower middleware
and will be carried through to the RPC.
Since response extensions cannot be set by interceptors the main use
case is to set them in RPCs and retrieve them in tower middlewares.
Figured that might be useful.
Fixes https://github.com/hyperium/tonic/issues/255

feat(tonic): add `Request` and `Response` extensions

---

tonic/src/transport/error.rs

At Embark we have a little helper function that converts a `&dyn
std::error::Error` into a `String` by walking the full chain of sources
(with `std::error::Error::source`) and joining them into a `String`.
We use that where we log errors to get as much information as possible
about whats causing an error. Works particularly well with anyhow's
`.context()` method.
However since `tonic::transport::Error` include its cause in their
`Display` impl we get the sources more than once.
As the cause can already be obtained through `std::error::Error::source`
no information should be lost by doing this.
Fixes https://github.com/hyperium/tonic/issues/632

fix(tonic): don't include error's cause in Display impl

---

tonic-web/tonic-web/src/service.rs
tonic/src/body.rs

Since the changement with the BoxBody #622 tonic-web wasn't compiling, the CI didn't detect it (this will be fixed with #648).
Make `tonic::body::empty_body` public and use it instead of the old and non existant anymore `BoxBody::empty()`

fix: cargo-web compilation

---

.github/assets/tonic-banner.svg

The logo is very hard to see on Github's dark mode :(
Use the same color that Github uses for icons / links in dark mode :)
Note that this is imperfect, since users can override dark mode on github, but I think that case is less common than someone who uses dark mode and keeps Github in dark mode (I don't have data to back this up, it just makes sense to me).

Use dark mode for docs logo

---

Cargo.toml
tests/root-crate-path/Cargo.toml
tests/root-crate-path/build.rs
tests/root-crate-path/foo.proto
tests/root-crate-path/src/main.rs
tonic-build/src/prost.rs

We shouldn't append `proto_path` (`super` by default) if the path starts
with `crate::`.
Fixes https://github.com/hyperium/tonic/issues/548

fix(build): generate root crate paths correctly

---

tonic/src/service/interceptor.rs

Fixes: #678
As mentioned in the issue authentication example is broken as `poll_ready` is not called on [`tower::buffer::Buffer`](https://github.com/tower-rs/tower/blob/tower-0.4.8/tower/src/buffer/service.rs#L146).
In `InterceptedService` propagate call to `poll_ready` to inner service.

fix(tonic): propagate call to `poll_ready` in `InterceptedService`

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/service/connection.rs

Fixes https://github.com/hyperium/tonic/issues/358

feat(tonic): expose setting for `http2_adaptive_window`

---

tonic/src/client/grpc.rs
tonic/src/codec/decode.rs
tonic/src/codec/prost.rs
tonic/src/status.rs
tonic/src/transport/server/recover_error.rs

A gRPC server may send a HTTP/2 GOAWAY frame with NO_ERROR status to gracefully shutdown a connection. This appears to Tonic users as a `tonic::Status` with `Code::Internal` and the message set to `h2 protocol error: protocol error: not a result of an error`.
The only way to currently detect this case and differentiate it from other internal errors (e.g., an application-level internal error) is to match on the message. A client may want to differentiate these cases because it may only want to alert on the application-level internal error and not on the transient transport-level issue. (Indeed, this is the use case for which I'm envisioning using this change.)
Matching on a message is not as robust, however, as matching on an `h2::Error` and its reason code. (The message could change for …

add h2::Error as a `source` for tonic::Status when converting from h2::Error

---

tests/integration_tests/Cargo.toml
tests/integration_tests/build.rs
tests/integration_tests/proto/stream.proto
tests/integration_tests/src/lib.rs
tests/integration_tests/tests/status.rs
tonic/src/codec/decode.rs
tonic/src/codec/encode.rs
tonic/src/status.rs

This fixes a bug found in #681 where sending a second status code in a stream would return an `Unknown` status code w/ the message that there was no `grpc-header`. From the grpc-h2 spec after the first status code returned in a streaming response we must end the stream. This change introduces the behavior with `infer_grpc_status` from trailers to map a `http::StatusCode::OK` to a empty/ended trailer stream. 
Closes #681

fix(codec): Fix streaming reponses w/ many status

---

tonic/src/client/grpc.rs
tonic/src/request.rs
tonic/src/service/interceptor.rs

`InterceptedService` would previously use `tonic::Request::into_http`
which removes reserved headers. That meant inner middleware in the stack
wouldn't be able to see those headers, which could result in errors.
Fixes https://github.com/hyperium/tonic/issues/700

fix(tonic): don't remove reserved headers in interceptor

---

examples/Cargo.toml
examples/src/mock/mock.rs
tests/compression/Cargo.toml

This just adds a new `mock` example showing how you can use the tokio `DuplexStream` to mock a in memory io connection between a client and server.

example: Add mocked io example

---

tonic/src/service/interceptor.rs

Updates the interceptor docs to mention tower-http's tracing middleware and improves the wording.
Fixes https://github.com/hyperium/tonic/issues/654

doc(tonic): mention tower-http's tracing middleware

---

examples/build.rs
examples/proto/attrs/attrs.proto
tonic-build/src/client.rs
tonic-build/src/lib.rs
tonic-build/src/prost.rs
tonic-build/src/server.rs

Implements #504.
Having the ability to add attributes to generated servers and clients allows things like feature gating or deriving additional service functionality without the need for a fork.
This PR only changes `tonic-build`. Four new methods are added to `Builder`:
| method | description |
| -------- | ----------- |
| `server_mod_attribute` | Adds a new attribute to the `mod` wrapping the server implementation. |
| `server_attribute` | Adds a new attribute to the service server `struct`. |
| `client_mod_attribute` | Adds a new attribute to the `mod` wrapping the client implementation. |
| `client_attribute` | Adds a new attribute to the service client `struct`. |
These are all optional values. Calling them more than once is additive. 
Each method accepts a `pattern` and an …

feat(build): support adding attributes to clients and servers

---

tonic/src/transport/server/mod.rs

Implementing `Clone` for `RouterService` makes it easier to use with `hyper::service::make_service_fn` and `tower::service_fn`. (For example, when using the pattern in [this example](https://github.com/hyperium/tonic/blob/master/examples/src/hyper_warp/server.rs#L54)).
Derive `Clone` for `RouterService`.

feat(tonic): derive Clone for RouterService

---

tonic-build/src/client.rs

This was accidentally committed as part of https://github.com/hyperium/tonic/pull/692.
Fixes https://github.com/hyperium/tonic/issues/718

fix(build): remove unnecessary `Debug` constraint for client streams

---

Cargo.toml
tests/service_named_service/Cargo.toml
tests/service_named_service/build.rs
tests/service_named_service/proto/foo.proto
tests/service_named_service/src/lib.rs
tonic-build/src/client.rs
tonic-build/src/server.rs

Fixes https://github.com/hyperium/tonic/issues/676

fix(build): allow services to be named `Service`

---

examples/src/tower/client.rs
examples/src/tower/server.rs
tonic-build/src/client.rs
tonic-build/src/server.rs
tonic/src/extensions.rs
tonic/src/request.rs
tonic/src/service/interceptor.rs
tonic/src/service/mod.rs
tonic/src/transport/server/mod.rs

Found myself wanting to be able to explicitly type a wrapped client (or server, for that matter), i.e.:
```
struct ClientWrapper {
client: Client<InterceptedService<Channel, MyInterceptor>>
}
```
This is currently impossible (until `impl`ing the `Fn` traits becomes stable, which will take a while).
Expose an `Interceptor` trait that is implemented for the function signatures of interceptors, but can also be implemented by downstream crates on custom types.
I think a semver change can be avoided by not renaming `interceptor_fn` -> `interceptor_layer`, but IMHO the name change is worthwhile.

feat(tonic): expose `Interceptor` trait

---

examples/src/interceptor/client.rs
examples/src/interceptor/server.rs

Some have asked how to use the new `Interceptor` trait to create named
interceptors. This updates the client example to show how to do that.

doc(tonic): add more interceptor examples

---

CHANGELOG.md
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

* **health:** Expose grpc_health_v1 file descriptor set ([#620](https://github.com/hyperium/tonic/issues/620)) ([167e8cb](https://github.com/hyperium/tonic/commit/167e8cb)), closes [#619](https://github.com/hyperium/tonic/issues/619)
* **tonic:** add `Interceptor` trait (#713) ([#713](https://github.com/hyperium/tonic/issues/713)) ([8c8f4d1](https://github.com/hyperium/tonic/commit/8c8f4d1))
* **tonic:** derive `Clone` for `RouterService` (#714) ([#714](https://github.com/hyperium/tonic/issues/714)) ([0a06603](https://github.com/hyperium/tonic/commit/0a06603))
* **transport:** Add `Connected` impl for `DuplexStream` (#722) ([#722](https://github.com/hyperium/tonic/issues/722)) ([0e33a02](https://github.com/hyperium/tonic/commit/0e33a02))
* **build:** remove unnecessary `Debug` constraint …

chore: Prepare tonic v0.5.1 and tonic-health 0.4.1

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

So as highlighted by https://github.com/hyperium/tonic/issues/730#issuecomment-895635088 it
turns out the new `Interceptor` trait required changes to tonic-build as
well, which I forgot to publish yesterday. Didn't see it because it wasn't
clear from the commit message.
So this bumps tonic _and_ tonic-build to 0.5.2 so we can release both.
There are no code changes.

chore: Prepare tonic+tonic-build v0.5.2

---

tonic/src/request.rs

Fixes #770
Request extensions are not passed properly to downstream service abstraction when using generated grpc clients. 
Make Request.map() copy `self.extensions`

fix(tonic): fix extensions disappearing during streaming requests

---

examples/src/autoreload/server.rs

Fix #798.
Set the std TCP listener to nonblocking mode. Tokio makes no assumptions towards TCP listeners from std before converting them to `tokio::net::TcpListener`, so setting nonblocking mode on must be done manually.

fix(examples): Fix autoreload example (#798)

---

examples/helloworld-tutorial.md

This PR makes some wording in the helloworld tutorial a little clearer.
Resolves #835

Fix wording in helloworld tutorial

---

README.md
examples/Cargo.toml
interop/Cargo.toml
rustfmt.toml
tests/ambiguous_methods/Cargo.toml
tests/compression/Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/included_service/Cargo.toml
tests/integration_tests/Cargo.toml
tests/root-crate-path/Cargo.toml
tests/same_name/Cargo.toml
tests/service_named_service/Cargo.toml
tests/stream_conflict/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tests/wellknown/Cargo.toml
tonic-build/Cargo.toml
tonic-health/Cargo.toml
tonic-reflection/Cargo.toml
tonic-types/Cargo.toml
tonic-web/Cargo.toml
tonic-web/tests/integration/Cargo.toml
tonic/Cargo.toml

Fixes https://github.com/hyperium/tonic/issues/843

chore: revert to 2018 edition

---

tonic/src/transport/mod.rs
tonic/src/transport/service/tls.rs
tonic/src/transport/tls.rs

Fix warnings about unused fields.
Remove a type that seems to be unused.

chore: fix warnings around unused TLS code

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

- Contains the revert to [rust 2018](https://github.com/hyperium/tonic/pull/847).
- Bumps both tonic and tonic-build.
- tonic-build goes from 0.6.0 to 0.6.2 since there was no 0.6.1. I
believe we want tonic and tonic-build versions to follow each other.

chore: Prepare 0.6.2

---

examples/src/streaming/server.rs

Typo in one of the comments from the streaming example.
https://github.com/hyperium/tonic/blob/master/examples/src/streaming/server.rs#L47
Fixed typo.

Fix typo in the streaming example.

---

examples/Cargo.toml
interop/Cargo.toml
tests/integration_tests/Cargo.toml

Update tracing-subscriber to version 0.3.
Update tracing-subscriber version to 0.3 and add `env-filter` that is removed from default features in this version. `interop` and `tests/integration_tests` use [`tracing_subscriber::fmt::SubscriberBuilder::with_env_filter`](https://docs.rs/tracing-subscriber/0.3.4/tracing_subscriber/fmt/struct.SubscriberBuilder.html#method.with_env_filter) and [`tracing_subscriber::EnvFilter`](https://docs.rs/tracing-subscriber/0.3.4/tracing_subscriber/struct.EnvFilter.html), but `examples` does not use `env-filter` feature because `tracing_subscriber::fmt()` returns `tracing_subscriber::fmt::SubscriberBuilder` and its `init` method does not use `env-filter` functionality.

chore: Update tracing-subscriber to 0.3

---

tonic/src/status.rs

Currently, when an error occurs at the H2 layer, it is transformed into a `tonic::Status` with a `source()` containing only the H2 error reason, instead of the full error. This loses a ton of context, as it is now impossible to know if the failure was caused by a protocol error, a general IO error (and if so, what what IO error), or something else entirely. It makes it much harder to debug problems.
It is unclear why this choice was made in #612. There's talk about `Clone` implementations causing this to be necessary, but I can't find that implementation.
This MR simply bubbles up the underlying `h2::Error`. `tonic::Status::source` will contain an `h2::Error` instead of an `h2::Reason`.

fix(tonic): Expose h2 error instead of reason

---

tonic-build/src/server.rs

I found myself in a situation where I wanted to spawn a task on a timer in the background that interacts with the data in a gRPC service that I spawned. With the current code that is generated for servers, in order to do that, I'd have to add a second and unnecessary layer of `Arc<Inner>` to be able to access my data from both the spawned task and the gRPC service.
This PR adds a second constructor `from_arc` to the generated server, allowing the user to pass in their own `Arc<Service>`, making the second layer of `Arc<T>` unnecessary.
The solution exposes the implementation detail of `Arc` being used internally to the user, making it harder to move away from using `Arc` if that should ever be desired.

feat(build): add constructor `from_arc` for gRPC servers

---

tonic/src/codec/mod.rs

I implemented a custom codec to use with a dynamic method where the types are not known at compile time. However this bound is mildly annoying since there's no sensible way to implement default
https://github.com/andrewhickman/grpc-client/blob/487c5409e78afef200a064c81ae1ade1b37c3c28/src/grpc/codec.rs#L63
The bound is never used so we can just remove it. I think this is technically a breaking change for consumers of the `Codec` trait, however anything using `ProstCodec`, like generated code, still works.

fix(codec): Remove `Default` bound on `Codec`

---

tonic-build/src/client.rs
tonic-build/src/server.rs

fix clippy warns: https://rust-lang.github.io/rust-clippy/master/#return_self_not_must_use

fix(build): clippy warning for must_use

---

tonic/src/codec/compression.rs

This change is for #879 . It allows for `identity` to be sent back as a `grpc-encoding` header as it requires no decompression
Some servers return `identity` as a `grpc-encoding` header
Allow the `identity` value of `grpc-encoding` to fall back to no compression

Add `identity` to `from_encoding_header`

---

interop/Cargo.toml
interop/src/bin/client.rs
interop/src/bin/server.rs

Change structopt to clap version 3.
Change structopt to clap version 3.

chore(interop): Change structopt to clap

---

tonic-build/src/client.rs
tonic/src/codegen.rs
tonic/src/service/interceptor.rs

This PR forwards `Interceptor` errors/`Status`es as valid HTTP responses, just like any other gRPC service generated by `tonic`.
In the very specific case of missing Content-Type headers when requests are intercepted, this PR fixes the bugs reported in #840 and #759.
In the more general case, this class of bug arose because interceptors and their statuses are treated differently from the rest of the gRPC service stack: their errors/`Status` are bubbled up as errors to be handled at the tower service layer, but not as a gRPC response. That means that a basic HTTP response is returned, sans trailers or headers of any kind (including the missing `Content-Type` header). [See this repository](https://github.com/NAlexPear/tonic-interceptor-response-repro) and [this …

fix: Handle interceptor errors as responses (#840)

---

tonic/src/transport/service/connector.rs

In getting started with tonic, I ran into an issue where issuing a first request with the default features and no explicit TLS configuration set would just result in a H2 `GoAway` frame without further context. Given that I was providing a `https` URL to the `Endpoint`, it seems reasonable that tonic should be able to give me a more meaningful error in this case.
If the URI scheme is `https` and the `tls` feature is disabled, return an error from the connector. If the feature is enabled but there is no TLS config present, also return an error.

fix: Return error on non https uri instead of panic

---

tonic-build/src/client.rs
tonic-build/src/server.rs
tonic/Cargo.toml
tonic/src/body.rs
tonic/src/codegen.rs
tonic/src/service/interceptor.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/service/mod.rs
tonic/src/transport/service/router.rs

This ports tonic's [previous routing setup](https://docs.rs/tonic/0.6.1/tonic/transport/server/struct.Router.html) to axum. This is mostly just a proposal. I think it lead to some decent wins but might not make that much difference in practice. Its a breaking change so we have to wait until 0.7 if we decide to go this way.
- The router type is no longer generic and conceptually simpler.
- Should resolve any compile time issues people might be having due to regression in Rust 1.56.
- Performance might be slightly better if users are routing between a lot of services. This is due to axum's router using [matchit](https://crates.io/crates/matchit) rather than the nested services.
- I also removed `Never` since axum requires services to use `Infallible`. Can easily convert between them but if …

feat(transport): port router to axum

---

tonic/src/transport/server/mod.rs

See Issue #900 
See Issue #900

fix(transport): Make server builder more consitient

---

tonic/src/client/grpc.rs
tonic/src/request.rs
tonic/src/service/interceptor.rs

See Issue #911 
The function for converting a Tonic request into an HTTP request, `Request::into_http`, is public only to the crate and only used in a few places. Currently, HTTP2 and POST are hardcoded for HTTP method and version. Thus, we can simply add `method` and `version` params and update the callers, and then fix the interceptor to preserve them.

fix(tonic): Preserve HTTP method in interceptor

---

tonic/src/status.rs

I want to have a `HashMap<Code, u64>` to keep some statistics on various codes servers return. But `Code` is not `Hash`. I don't see any reason why it would not be. It's just a simple enum.
I can of course keep a `HashMap<u32, u64>` and upon insertion cast the enum to an integer. But I don't know the width of the integer as it's not part of the public API. And it also does not allow me to get the nice string description of the code out of the hashmap keys later.
Implement `Hash` for `Code`.

feat: Implement hash for `Code`

---

tonic/src/transport/channel/endpoint.rs

fix(transport): Endpoint returns transport error

---

tests/integration_tests/tests/status.rs
tonic/src/transport/channel/endpoint.rs

fix(transport): connect w/ connector infailable

---

tonic-web/src/lib.rs

Currently, `tonic-web` use the tonic-reflection doc url.
Fixed it.

fix(web): Fix error tonic-web doc url

---

tonic/src/transport/server/mod.rs

The current behavior is to replace the previous layer with the newly specified layer.  The new behavior is to chain the layers together.  The current behavior might actually be intentional, but IMO it's not very intuitive given how services are added by chaining method calls.
I can adjust the docs and/or tests as necessary, so let me know if you want me to do so.
We were using `Server::layer()` and assumed it supported more than one layer (without using `Stack` from `tower`) given the example in the docs (which has an interceptor for authentication that, with the current behavior, gets replaced with effectively an identity interceptor afaict).
This change basically just uses `Stack` internally rather than requiring users to use it themselves manually.

fix(transport): Make `Server::layer()` support more than one layer

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/mod.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/executor.rs
tonic/src/transport/service/mod.rs

At Embark we've been working on integrating tokio-console into our project and have used `hyper::client::Builder::executor` to pass our own executor that spawns named tasks. However its not possible to do that tonic, so tasks spawned by tonic are left unnamed.
- Add tonic's own `Executor` trait. Its identical to hyper's but added here not to have a public dependency on hyper.
- Added `Endpoint::executor` builder method to support setting another executor.
- Spawn `tower::buffer::Buffer` tasks on the given executor.
- Still uses `tokio::spawn` by default.
I intentionally didn't touch the server side because we don't need that at Embark but could do that if we think its relevant.

feat(transport): support customizing `Channel`'s async executor

---

examples/Cargo.toml
interop/Cargo.toml
tests/ambiguous_methods/Cargo.toml
tests/compression/Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/included_service/Cargo.toml
tests/integration_tests/Cargo.toml
tests/root-crate-path/Cargo.toml
tests/same_name/Cargo.toml
tests/service_named_service/Cargo.toml
tests/stream_conflict/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tests/wellknown/Cargo.toml
tonic-build/Cargo.toml
tonic-health/Cargo.toml
tonic-reflection/Cargo.toml
tonic-types/Cargo.toml
tonic-web/tests/integration/Cargo.toml
tonic/Cargo.toml

Signed-off-by: Jesse Szwedko <jesse@szwedko.me>

feat: Update prost to 0.10

---

tonic/Cargo.toml

The tokio ecosystem has been moving to tokio-util 0.7 -- e.g. h2 has just upgraded to it. In my project, tonic is the only holdout still on 0.6, so if we upgrade, my project will have fewer crates to compile.
Bump tokio-util from 0.6 to 0.7

chore: Update tokio-util to 0.7

---

tonic-build/src/prost.rs
tonic/src/service/interceptor.rs
tonic/src/transport/server/conn.rs
tonic/src/transport/server/mod.rs

Fixes clippy warnings.
Updates.

chore: Fix clippy lints

---

tonic-build/src/lib.rs
tonic-build/src/prost.rs

Exposing such plugin allows independent code generators (outside of the vanilla `build.rs` workflow) to use tonic-build to get gRPC code generation. This paves the way for a `protoc-gen-tonic` plugin, opening integration in e.g. buf.
And indeed, you can find the plugin over here: https://github.com/Tuetuopay/protoc-gen-tonic
This builds on my work on [`protoc-gen-prost`](https://github.com/Tuetuopay/protoc-gen-prost), and allows integration in the wider protoc/buf/... ecosystem. You can read more on the motivation for such a change over on https://github.com/tokio-rs/prost/pull/492, and more about the features in the prost plugin repository. The tonic plugin inherits from all nice features (like crate gen) from the prost plugin.

feat(build): Expose Prost generation plugin

---

CHANGELOG.md
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-reflection/Cargo.toml
tonic-web/Cargo.toml
tonic/Cargo.toml
tonic/src/lib.rs

* Update prost to 0.10 ([#948](https://github.com/hyperium/tonic/issues/948)) ([c78274e](https://github.com/hyperium/tonic/commit/c78274e3fe5763cba291a605979cd7175ad6c38f))
* **build:** use prettyplease to format output ([#890](https://github.com/hyperium/tonic/issues/890)) ([#904](https://github.com/hyperium/tonic/issues/904)) ([d6c0fc1](https://github.com/hyperium/tonic/commit/d6c0fc112b2288a080fd0a727453b24d666e3d79))
* **tls:** upgrade to tokio-rustls 0.23 (rustls 0.20) ([#859](https://github.com/hyperium/tonic/issues/859)) ([4548997](https://github.com/hyperium/tonic/commit/4548997080c9c34f12dc0ff83ab0e2bb35ceca9c))
* **transport:** port router to axum ([#830](https://github.com/hyperium/tonic/issues/830)) ([6dfc20e](https://github.com/hyperium/tonic/commit/6dfc20e1db455be12b0a647533c …

chore: Prepare 0.10 release

---

interop/src/bin/client.rs

Follows rust's naming convention.
Uses clap's rename_all option instead of lint allowing.

chore(interop): Use clap rename_all option instead of lint allowing

---

tonic-web/README.md

Enhances document.
- Fixes typos.
- Reduces release tasks.

chore(web): Minor enhancement in document

---

tonic/Cargo.toml
tonic/src/lib.rs
tonic/src/transport/mod.rs

feat(transport): Add `channel` feature flag

---

examples/Cargo.toml
examples/src/tls/client_rustls.rs
examples/src/tls/server_rustls.rs

This PR adds both a client and server example that uses rustls and tokio-rustls directly rather than going through the `transport` module (except for the server which uses the router from that module).

chore: Add rustls examples

---

tonic/Cargo.toml

The default features in tower enable log support in tracing, which unfortunately makes a lot of user code non-send. In other words, this feature is not additive and thus tower should probably not be enabling it anyways, especially by default.

fix: don't enable default features in tower

---

tests/integration_tests/Cargo.toml
tests/integration_tests/tests/client_layer.rs
tonic-build/src/client.rs

https://github.com/hyperium/tonic/issues/973
It seems the `Default` bound was overly restrictive
Move the `Default` bound to the `with_interceptor` function instead of the whole impl

fix(build): Reduce `Default` bound requirement

---

examples/Cargo.toml
tests/compression/Cargo.toml
tests/integration_tests/Cargo.toml

I noticed [CI was failing](https://github.com/hyperium/tonic/runs/6192574486?check_suite_focus=true) probably because of an update to tower-http. This'll fix that.

chore: update tower-http

---

examples/src/authentication/client.rs
examples/src/authentication/server.rs
examples/src/gcp/client.rs
interop/src/client.rs
tonic/src/metadata/value.rs
tonic/src/request.rs

As described [in the issue](https://github.com/hyperium/tonic/issues/986) there are several adhoc methods that say "This function is intended to be replaced in the future by a `TryFrom` implementation once the trait is stabilized in std." Well, TryFrom is stable in std now, so let's use it :)
I looked at which TryFrom impls [http::HeaderValue](https://docs.rs/http/latest/http/header/struct.HeaderValue.html) has, and copied those where it made sense. Seems like MetadataValue is _mostly_ a copy of http::HeaderValue, so I thought it was a good guide.
I tried to avoid repeating code, so often various TryFrom implementations either call into each other, or into the underlying `http::HeaderValue` TryFrom implementations. I kept the #[inline] attribute when the original call had it, and added a …

feat: Add TryFrom implementations for MetadataValue

---

tonic/src/metadata/encoding.rs

`MetadataValue::from<i16>` and other numeric types aren't shown in Rustdoc, because they're implemented for `Metadata<Ascii>`, and Ascii is hidden.
The [docs for MetadataValue](https://docs.rs/tonic/0.7.1/tonic/metadata/struct.MetadataValue.html) don't show any of its `From<>` impls for numerics like i16/i32/usize/etc. 
Unhide the docs. I understand this makes the docs a bit noisier, so if there's a better solution I'd be open to that instead.

tonic: Unhide docs for Ascii and Binary

---

tonic/src/transport/service/connector.rs

https://github.com/hyperium/tonic/pull/838 breaks custom connectors that do tls in some other way (in my case, `tokio-native-tls`
Remove the error that was added in the other pr, if `tls` is not enabled

fix(transport): Emit `HttpsUriWithoutTlsSupport` only w/ tls feat

---

examples/Cargo.toml
examples/build.rs
examples/src/json-codec/client.rs
examples/src/json-codec/common.rs
examples/src/json-codec/server.rs
tonic-build/src/client.rs
tonic-build/src/lib.rs
tonic-build/src/manual.rs
tonic-build/src/prost.rs
tonic-build/src/server.rs

@LucioFranco after we chatted briefly on discord yesterday I did a bit more thinking about how improve accessibility of the code generation functionality in tonic-build. This is one potential approach. Its in a WIP state but I wanted to get your thoughts and see if this is something you'd be interested in as a contribution to tonic. If so I can spend some time actually making it usable.
gRPC is a general purpose RPC framework that, while generally is paired with protobuf, is agnostic to the type of serialization format used for messages and in some cases it may be desired to use a different serialization format other than protobuf. 
This PR takes a look at one possible way to enable using a custom, non-protobuf codec for serializing messages to the wire. This is done via:
- changing the …

feat(build): Better support for custom codecs

---

examples/helloworld-tutorial.md

I was a bit confused in the tutorial about where to put build.rs, and think this small change might help other people learning rust who use the tutorial helloworld-tonic.
Slightly change wording to emphasize location of build.rs is in root and not /src.

Small wording change for newbie-friendly clarity

---

tonic/src/codec/decode.rs

I was not clear what the difference between `Err(_)` and `Ok(None)` was and asked on the discord channel. @davidpdrsn gave a compelling answer which makes sense to put in the docs.
Document the return values of `Streaming::message()`.

docs: document Streaming::message() return values

---

interop/Cargo.toml
interop/src/bin/client.rs
interop/src/bin/server.rs

Clap recently added new deprecations in 3.2. Because we deny warnings, these deprecation warnings end up as build failures. 
This resolves those deprecations by updating to the usage to match the new API.

chore: update clap dependency, fix deprecations

---

tonic-reflection/src/server.rs

Refactoring.
Follows to the document of [`write_fmt`](https://doc.rust-lang.org/stable/std/fmt/trait.Write.html#method.write_fmt).

chore(reflection): Use write macro instead of write_fmt

---

tests/integration_tests/tests/origin.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/service/add_origin.rs
tonic/src/transport/service/connection.rs

At @znly, we use Envoy as a service mesh to distribute the traffic across the services.
Meaning that:
- we have an auto-scaled farm of Envoy which proxy the entire traffic.
- we have to refresh the IPs periodically (due to auto-scaling).
- we have to talk to the IPs directly.
That said, the requests end with an unavailable error, why? because Envoy is called with the URI (the IP in our case) and can't determine which service we are trying to reach.
A new method named `origin` has been added to override the origin sent.
We tried it in production and it's working fine.
Let me know if you have a better solution.

tonic: Introduce a new method on Endpoint to override the origin

---

tonic-build/src/prost.rs

Fixes: #1020
Refs: #1019
Currently, tonic-build does not emit cargo:rerun-if-changed
instructions. This will cause the build script to be rerun if any file
changes in the package.
This PR implements an option on the Builder called
emit_rerun_if_changed that, when enabled, will emit the
cargo:rerun-if-changed instructions for all of the proto file paths
and include directories.

feat(build): Add option to emit rerun-if-changed instructions

---

tonic/src/transport/channel/endpoint.rs

typo in comment -- showing in my IDE. :)
typos are bugs
fix the typo

chore(doc): Fix typo in endpoint docs

---

tonic-reflection/src/server.rs

Makes it easier to store a reflection server in a variable or get the gRPC service's name.

reflection: export server types

---

tonic-reflection/src/server.rs

reflection: add `with_service_name` method

---

tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs

We call the `serve_with_shutdown` method of tonic::transport::server::Router passing a local socket address. If the server is unable to bind the address, that returns an Err (quite quickly). If it *is* able to bind the address, it returns Ok only much later, when serving is complete.
We'd like to know when(/whether) the server has successfully bound the address, i.e. as soon as we know that bind isn't going to fail, and when a client can begin connecting to it (avoiding any race condition).
The above can be done using the `serve_with_incoming_shutdown` method instead, passing a `TcpIncoming` struct - exactly as `serve_with_shutdown` does (it first builds the TcpIncoming, which binds the socket and may fail; and then passes that to the serve_with_incoming... method). By performing these …

Make TcpIncoming public

---

.github/workflows/CI.yml
CHANGELOG.md
examples/Cargo.toml
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
interop/Cargo.toml
tests/ambiguous_methods/Cargo.toml
tests/compression/Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/included_service/Cargo.toml
tests/integration_tests/Cargo.toml
tests/root-crate-path/Cargo.toml
tests/same_name/Cargo.toml
tests/service_named_service/Cargo.toml
tests/stream_conflict/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tests/wellknown/Cargo.toml
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-reflection/Cargo.toml
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/tests/integration/Cargo.toml
tonic/Cargo.toml
tonic/src/lib.rs

* Add `Grpc::with_origin` for clients ([#1017](https://github.com/hyperium/tonic/issues/1017)) ([10f6d2f](https://github.com/hyperium/tonic/commit/10f6d2f1a9fa3969599ebd674f7be27f4f458754))
* **build:** Add option to emit rerun-if-changed instructions ([#1021](https://github.com/hyperium/tonic/issues/1021)) ([1d2083a](https://github.com/hyperium/tonic/commit/1d2083a1a690edcb3f95343edfe229339c4257b7))
* **build:** Better support for custom codecs ([#999](https://github.com/hyperium/tonic/issues/999)) ([de2e4ac](https://github.com/hyperium/tonic/commit/de2e4ac077c076736dc451f3415ea7da1a61a560))
* Decouple `NamedService` from the `transport` feature ([#969](https://github.com/hyperium/tonic/issues/969)) ([feae96c](https://github.com/hyperium/tonic/commit/feae96c5be1247af368e6ce665c8df757d298e …

chore: Prepare 0.8 release

---

tonic/src/lib.rs

The [current docs](https://docs.rs/tonic/0.8.0/tonic/index.html#feature-flags) still reference the outdated feature flag `compression`, which has been superseded by `gzip` in `tonic` and removed from `tonic-build` entirely.
See #1004 (commit a585a72) for more information on the changes to the `compression` feature in `tonic` `0.8`.
Have the docs reflect the current state of the crate(s).
Fix the `tonic` docs to reference `gzip` and to no longer state that `tonic-build` also needs a flag to be specified.

Update docs to reflect changes to compression feature

---

tonic/src/client/grpc.rs
tonic/src/codec/decode.rs
tonic/src/codec/encode.rs
tonic/src/status.rs
tonic/src/transport/server/incoming.rs

`tonic` has a lot of generic code which causes a lot of monormorphization and therefore bloated compile times and binaries. 
By extracting code which does not need to be generic over a type parameter into non generic (or less generic functions) we can reduce how much code gets instantiated and passed to LLVM.
This gives a ~23% reduction in the output of LLVM IR (according to `cargo llvm-lines -p examples --bin streaming-client`) and reduces the compilation time of `cargo build --release --bin streaming-client` by ~1.5s (21s to 19.5s). (Measured by just switching branches between this one and master to force recompilations)
```
Lines         Copies       Function name
-----         ------       -------------
Lines         Copies       Function name
-----         ------       ------------- …
```

refactor: Reduce how much code gets monomorphized

---

tonic/src/extensions.rs
tonic/src/status.rs

Expose Extensions::into_http and Status::from_error as public.
See #910. These functions must be public in order to implement async_interceptor in its own external crate.

Expose Extensions::into_http and Status::from_error

---

tonic/src/status.rs

Fixes https://github.com/hyperium/tonic/issues/1075
Turns out using `Arc<dyn Error>` for the status makes `Status` cloneable. Users sometimes ask about this and I think it makes sense to support.

feat(tonic): impl `Clone` for `Status` using `Arc`

---

tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/src/generated/grpc.health.v1.rs
tonic-types/src/generated/google.rpc.rs

Closes #1073
I also documented the feature flags.

feat(build): add `cleanup-markdown` feature flag

---

tonic/Cargo.toml

fix(transport): Bump axum for CVE-2022-3212

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

* **transport:** Bump axum for CVE-2022-3212 ([#1088](https://github.com/hyperium/tonic/issues/1088)) ([cddd992](https://github.com/hyperium/tonic/commit/cddd99266682127a3fa0e5d601f56a6346369814))
* **tonic:** add `Result<T>` type alias for `std::result::Result<T, tonic::Status>` ([#1085](https://github.com/hyperium/tonic/issues/1085)) ([56ff45d](https://github.com/hyperium/tonic/commit/56ff45d9a36040c429753d0d118ad980fbfe3eb8))
* **build:** add `cleanup-markdown` feature flag ([#1086](https://github.com/hyperium/tonic/issues/1086)) ([c1b08df](https://github.com/hyperium/tonic/commit/c1b08dffacb67e13ce7e94a002eee8999ca7c0e5))
* **tonic:** impl `Clone` for `Status` using `Arc` ([#1076](https://github.com/hyperium/tonic/issues/1076)) …

chore: Prepare `0.8.2` release

---

tonic/Cargo.toml

There is a security vulnerability in the `axum-core` crate ([RUSTSEC-2022-0055](https://rustsec.org/advisories/RUSTSEC-2022-0055)), which is used in `axum` and subsequently `tonic`.
I'm not sure if directly impacts `tonic` or not, but it may be related to https://github.com/hyperium/tonic/issues/1097.
Proposing to upgrade the version of `axum` to 0.5.16, which contains the patched version of `axum-core`.

chore: bumping dependency `axum` to version 0.5.16

---

tonic-web/src/service.rs

The grpc_web_content_types() test function had a duplicate `GRPC_WEB_PROTO` in the array, where one of these should have been `GRPC_WEB_TEXT_PROTO`.

test(tonic-web): fix grpc_web_content_types() test not covering all cases

---

tonic/src/request.rs

Fix #1116
See #1116
This PR contains two changes:
* One as described in #1116 to expose `Request#into_parts`
* Another one is to expose `from_parts`, in order to have a symmetric api, consistent with `http::Request` as well (see https://docs.rs/http/0.2.8/http/request/struct.Request.html#method.into_parts and https://docs.rs/http/0.2.8/http/request/struct.Request.html#method.from_parts)

Expose `Request#into_parts` and `Request#from_parts`

---

tonic-web/Cargo.toml
tonic-web/src/config.rs
tonic-web/src/layer.rs
tonic-web/src/lib.rs
tonic-web/src/service.rs
tonic-web/tests/integration/tests/grpc_web.rs

Implement tower::Layer for tonic_web::Config

---

Cargo.toml
tonic-build/Cargo.toml

```text
error: failed to load source for dependency `prost-build`
Caused by:
Unable to update https://github.com/tokio-rs/prost/?branch=lucio/format
Caused by:
failed to fetch into: /Users/roger/.cargo/git/db/prost-93ab2781ba9c857f
Caused by:
process didn't exit successfully: `git fetch --force --update-head-ok 'https://github.com/tokio-rs/prost/' '+refs/heads/lucio/format:refs/remotes/origin/lucio/format'` (exit status: 128)
--- stderr
fatal: Unable to find remote reference refs/heads/lucio/format
```

fix: remove patch caused cargo error

---

Cargo.toml
tests/disable_comments/.gitignore
tests/disable_comments/Cargo.toml
tests/disable_comments/build.rs
tests/disable_comments/proto/test.proto
tests/disable_comments/src/lib.rs
tests/disable_comments/tests/disable_comments.rs
tonic-build/src/client.rs
tonic-build/src/manual.rs
tonic-build/src/prost.rs
tonic-build/src/server.rs

In [prost-build](https://crates.io/crates/prost-build)'s Configurations, there is a disable_comments. This disables the generation of comments in proto as documentation comments. However, it only works for message and its fields, not service and its rpc.
This Pull Request adds similar functionality to [tonic-build](https://crates.io/crates/tonic-build)'s Configurations.
- Add disable_comments to [`tonic_build::Builder`](https://docs.rs/tonic-build/latest/tonic_build/struct.Builder.html).
- The documentation generation points for [tonic_build::server::generate](https://docs.rs/tonic-build/latest/tonic_build/server/fn.generate.html) and [tonic_build::client::generate](https://docs.rs/tonic-build/latest/tonic_build/client/fn.generate.html) have been changed.

Add disable_comments option

---

tonic/src/codec/encode.rs
tonic/src/codec/prost.rs

Fixes #1141.
Replace assertion w/ an ordinary error path.

fix: do not panic while encoding oversized bodies

---

tonic/Cargo.toml
tonic/src/transport/server/mod.rs
tonic/src/transport/service/router.rs

Updates to axum 0.6.0. No visible changes for tonic.

chore: update to axum 0.6.0

---

tonic-build/Cargo.toml
tonic-build/src/client.rs
tonic-build/src/code_gen.rs
tonic-build/src/lib.rs
tonic-build/src/manual.rs
tonic-build/src/prost.rs
tonic-build/src/server.rs

This commit adds a new `CodeGenBuilder` that replaces the client/server generate fn with a builder stlye that allows adding config items in an non-breaking way. This also deprecates both of the client/server generate fn in favor of the builder ones.

feat(build): Add `CodeGenBuilder`

---

CHANGELOG.md
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

Included in this release is also the sub-crate major version bumps:
* `tonic-health` has been bumped to `0.8.0`
* `tonic-reflection` has been bumped to `0.6.0`
* `tonic-web` has been bumped to `0.5.0`
* do not panic while encoding oversized bodies ([#1142](https://github.com/hyperium/tonic/issues/1142)) ([33e22bb](https://github.com/hyperium/tonic/commit/33e22bbc5ef1b74de82394c3ebfea27382419620)), closes [#1141](https://github.com/hyperium/tonic/issues/1141)
* **reflection, health:** Remove transport feature ([#1112](https://github.com/hyperium/tonic/issues/1112)) ([7153289](https://github.com/hyperium/tonic/commit/7153289b51f7770cdd00cefeceddacc4cf36df97))
* **build:** Add `build_transport` builder option ([#1130](https://github.com/hyperium/tonic/issues/1130)) …

chore: Prepare `v0.8.3` release

---

interop/Cargo.toml

Follows to the latest version.

chore(interop): Update to console 0.15

---

tonic-build/src/code_gen.rs
tonic-build/src/lib.rs
tonic-build/src/manual.rs
tonic-build/src/prost.rs

Changes `CodeGen8uilder` to `CodeGenBuilder` in `tonic_build`. Fixes #1165.
While `8builder` looks super l33t, it's not consistent with the documentation.
`sed -i 's/CodeGen8uilder/CodeGenBuilder/g'`

Fix CodeGen8uilder typo

---

examples/Cargo.toml
examples/src/blocking/server.rs

- Moves to the blocking directory.
- Registers the blocking server example as bin.
- Fixes lint.
- Applies rustfmt.

chore(examples): Fix blocking-server

---

tonic-build/src/client.rs
tonic-build/src/lib.rs
tonic-build/src/server.rs

See: https://github.com/hyperium/tonic/pull/1127#discussion_r1016758800
---
@LucioFranco 
I didn't understand how to centralize the impls, so I would like you to comment on the draft PRs.

Follow up #1127

---

.github/workflows/CI.yml
README.md

Tonic's msrv might be 1.60 due to axum 0.6.

chore: Bump msrv to 1.60

---

.github/workflows/CI.yml
deny.toml

Updates it to support current project status.

chore: Update cargo-deny config

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/debug_info.rs
tonic-types/src/richer_error/std_messages/mod.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1095]. It adds support for the `DebugInfo` standard error message type to `tonic-types`.
[#1095]: https://github.com/hyperium/tonic/pull/1095

feat(types): Add gRPC Richer Error Model support (DebugInfo)

---

tonic/Cargo.toml
tonic/src/codec/prost.rs

We could use namespaced dependency feature introduced in Rust 1.60.

chore: Use namespaced dependency feature

---

tonic-build/src/server.rs
tonic-health/src/generated/grpc.health.v1.rs
tonic-reflection/src/generated/grpc.reflection.v1alpha.rs
tonic/benches-disabled/benchmarks/compiled_protos/helloworld.rs

This PR changes the generated code to use the unified function syntax for cloning `Arc` values (`Arc::clone(foo)` instead of `foo.clone()`).
In https://github.com/MaterializeInc/materialize, we use tonic, and we also enforce the clippy lint [`clone_on_ref_ptr`](https://rust-lang.github.io/rust-clippy/stable/index.html#clone_on_ref_ptr). This lint currently triggers on code generated by tonic, which forces us to disable it for modules that import tonic-generated code.
The main motivation for this PR is that we don't have to disable the lint anymore. Using unified function syntax when cloning `Arc`s also makes the code more obvious, which is nice.
Adjust the generated code to conform with the style clippy proposes.

tonic-build: use unified syntax to clone `Arc`s

---

.github/workflows/CI.yml
tonic-types/src/richer_error/mod.rs

chore: Add clippy to ci

---

.github/workflows/CI.yml

Improves the ci code style consistency.

chore: Use RUSTFLAGS in clippy job for style consistency

---

.github/workflows/CI.yml

Updates to actions/checkout version 3 and uses it instead of master branch version.

chore: Use actions/checkout@v3 in ci

---

.github/workflows/CI.yml

- Uses hecrj/setup-rust-action which has been used before in tonic project as it's been updated more frequently than actions-rs/toolchain recently.
- Locks hecrj/setup-rust-action version to v1 to be safe against possible breaking changes.
- Uses hecrj/setup-rust-action's option to install components.

chore: Use setup-rust-action v1 to setup rust in ci

---

examples/Cargo.toml

pin-project seems not to be used in examples.

chore(examples): Remove unused pin-project from dependencies

---

.github/workflows/CI.yml

In every check ci jobs, it takes about 3 (in ubuntu-latest), 4 (in windows-latest), 5 (in macOS-latest) minutes to install cargo-hack. This pull request tries to speed up the jobs by introducing [baptiste0928/cargo-install](https://github.com/baptiste0928/cargo-install) action using cache.

chore: Use baptiste0928/cargo-install@v1 to install cargo-hack

---

examples/Cargo.toml

Uses `required-features` in binary targets in order to clarify examples dependencies.

chore(examples): Clarify dependencies

---

.vscode/settings.json
Cargo.toml
tests/service_named_result/Cargo.toml
tests/service_named_result/LICENSE
tests/service_named_result/build.rs
tests/service_named_result/proto/result.proto
tests/service_named_result/src/lib.rs
tonic-build/src/client.rs
tonic-build/src/server.rs
tonic-health/src/generated/grpc.health.v1.rs
tonic-reflection/src/generated/grpc.reflection.v1alpha.rs

Fixes a name conflict when the service itself is named as `Result`. The conflict occurs with the `std::result::Result` included in the prelude. Issue described in #1156.
To prevent the conflict, the generated code will now refer to the `Result` in a qualified manner viz, `std::result::Result`.
**result.proto**
```protobuf
syntax = "proto3";
import "google/protobuf/any.proto";
import "google/protobuf/empty.proto";
option go_package = "github.com/stevenhansel/binus-logbook/scraper/internal/grpc/proto/result";
package result;
service Result {
rpc Listen(google.protobuf.Empty) returns (Reply) {}
}
message Reply {
int32 step = 1;
string name = 2;
}
```
**server.rs**
```rust
use tonic::{transport::Server, Request, Response, Status};
pub mod pb {
tonic::include_proto!("result");
}
use …
```

Fixes: #1156 Prevent error when "Result" is used as name of service in proto 

---

tonic-reflection/src/server.rs

Allows grpcurl to use reflection. 
Returns a dummy response against an all_extension_numbers_of_type request instead of an error response. This is a workaround approach to  https://github.com/hyperium/tonic/issues/1077. As extensions are not supported in prost (https://github.com/tokio-rs/prost/issues/674), we might not be able to handle it in tonic layer.

feat(reflection): Add dummy implementation for extension

---

tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/src/lib.rs
tonic-types/src/lib.rs

Improves tests.
Add tests to try decode the byte encoded file descriptor set.

chore: Add test to check FILE_DESCRIPTOR_SET is valid

---

.github/workflows/CI.yml
tonic-reflection/src/lib.rs
tonic-types/src/lib.rs
tonic/src/metadata/map.rs
tonic/src/metadata/value.rs

Fixes doc warnings and adds a ci job to run cargo doc.

chore: Fix doc warning

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/mod.rs
tonic-types/src/richer_error/std_messages/quota_failure.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1179]. It adds support for the `QuotaFailure` standard error message type to `tonic-types`.
[#1179]: https://github.com/hyperium/tonic/pull/1179

feat(types): Add gRPC Richer Error Model support (QuotaFailure)

---

examples/Cargo.toml
examples/src/gcp/client.rs
examples/src/tls/client.rs
examples/src/tls/server.rs
examples/src/tls_client_auth/client.rs
examples/src/tls_client_auth/server.rs
examples/src/uds/server.rs

Simplifies examples.
Uses the standard library to read data for examples instead of tokio's file api. In our examples we don't need to read the data asynchronously.

chore(examples): Remove unnecessary asyncronous file io to read data for example

---

tonic/src/transport/service/discover.rs

I'm using [ginepro](https://github.com/TrueLayer/ginepro) for client-side load balancing, and I'm seeing ~75s timeouts ([seemingly from the kernel](https://stackoverflow.com/questions/8471577/linux-tcp-connect-failure-with-etimedout)) when trying to connect to a host which doesn't respond. I'd like more control over this timeout duration.
I already set a `connection_timeout` in the `Endpoint`, which can be used here.
Use the connection timeout value from the `endpoint` supplied.

Set a connection timeout in DynamicServiceStream

---

examples/src/gcp/client.rs
examples/src/routeguide/data.rs
examples/src/tls/client.rs
examples/src/tls/client_rustls.rs
examples/src/tls/server.rs
examples/src/tls/server_rustls.rs
examples/src/tls_client_auth/client.rs
examples/src/tls_client_auth/server.rs

Allows to run examples in the examples directory as well as the workspace root.
Uses an absolute path instead of a relative path when reading data for examples.

chore(examples): Remove relative path from reading data

---

tonic/src/transport/error.rs

This lint annotation seems not to be needed now.

chore(tonic): Remove outdated allow lint

---

tonic-health/src/lib.rs
tonic-health/src/server.rs
tonic-reflection/src/lib.rs
tonic-reflection/src/server.rs
tonic-reflection/tests/server.rs

Resolves #1221.
> **Warning**: This pull request includes breaking changes.
Renames modules and variables.

feat: Rename protobuf api

---

tonic-web/tests/integration/Cargo.toml
tonic-web/tests/integration/src/lib.rs
tonic-web/tests/integration/tests/grpc_web.rs

I overlooked the integration test of tonic-web in #1228.

chore(web): Update to base64 0.21

---

tonic/src/transport/service/tls.rs

We could remove this lint annotation.

chore(tonic): Remove outdated allow dead code lint annotation

---

interop/Cargo.toml

In order to fix msrv 1.60 test, locks clap version to 4.0 as clap 4.1 increased its msrv to 1.64.

chore(interop): Lock clap version to 4.0

---

tests/disable_comments/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tonic-build/Cargo.toml
tonic-build/src/prost.rs

The latest prost-build introduced [enum_attribute](https://docs.rs/prost-build/0.11.6/prost_build/struct.Config.html#method.enum_attribute) and [message_attribute](https://docs.rs/prost-build/0.11.6/prost_build/struct.Config.html#method.message_attribute) configurations. We should support it.
Update prost-build to v0.11.6 and add the enum_attribute and message_attribute forwarders.

tonic-build: Builder: add {enum,message}_attributes

---

deny.toml

Fixes cargo-deny check.
Adds windows-sys to cargo-deny's skip-tree config. Since this crate is a fundamental crate to support windows, a lot of crates depend on it. As each of them defines their own update policies, it seems to be difficult to use one version of it entirely in dependency tree always.

chore: Add windows-sys and hermit-abi to cargo-deny skip-tree

---

interop/Cargo.toml
interop/src/bin/client.rs
interop/src/bin/server.rs

We have used clap to parse arguments in interop. This crate provides us with a lot of great functionalities. Since clap evolves quickly, its increase of msrv is relatively rapid. As we uses clap only in test crate, we might not need most of the clap's functionality. In order to reduce effects from dependencies in our test crates, we could use the other arguments parser which is aimed to be simple.
Uses a more lightweight arguments parser library.

chore(interop): Use pico-args instead of clap

---

.github/workflows/CI.yml
examples/Cargo.toml
interop/Cargo.toml
tests/ambiguous_methods/Cargo.toml
tests/compression/Cargo.toml
tests/disable_comments/Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/included_service/Cargo.toml
tests/integration_tests/Cargo.toml
tests/same_name/Cargo.toml
tests/service_named_result/Cargo.toml
tests/service_named_service/Cargo.toml
tests/stream_conflict/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tests/wellknown/Cargo.toml

Keeps manifests not to depend on unused crates.
Adds [cargo-machete](https://github.com/bnjbvr/cargo-machete) to detect unused dependencies.

chore: Add cargo-machete to detect unused dependencies

---

tonic/src/metadata/key.rs

I tried using `BinaryMetadataKey::from_bytes` to parse a header value, but noticed it inconveniently panics on values that don't end in `-bin`.
I assume this is a bug since the signature of this function suggests it returns an error on failure, and the documentation makes no mention of panicking.
This PR fixes it to return an error instead.

Fix panic in MetadataKey::from_bytes

---

tonic-health/tests/bootstrap.rs

Adds a generation process of file descriptor set, which has been already committed.

chore(health): Generate file descriptor set in bootstrap test

---

tonic/src/status.rs

I'm writing a grpc transport layer based on the transport module of tonic. Currently a few bits of `Status` are `pub(crate)` so they can be used by transport, but not if the code is pulled into a separate crate.
Change some `pub(crate)` to `pub` and add a public setter method.

Make some functionality of Status public

---

tonic/src/response.rs

In cases when you have to build for example an L7 gRPC proxy with data injection into responses from downstream API it's required to perform copying the whole responses to shift ownership this can be easily avoided by implementing the approach suggested for Request in PR: https://github.com/hyperium/tonic/pull/1118
This PR contains two changes:
One is to expose `Response#into_parts` to easily control the ownership without making unnecessary copying. 
Another one is to expose `Response#from_parts`, in order to have a symmetric API, consistent with `Request` as well

Expose `Response#into_parts` and `Response#from_parts`

---

tonic/src/service/interceptor.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/service/router.rs

We can use `NamedService` without the transport feature.

feat(tonic): Use NamedService without transport feature

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/error_info.rs
tonic-types/src/richer_error/std_messages/mod.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1204]. It adds support for the `ErrorInfo` standard error message type to `tonic-types`.
[#1204]: https://github.com/hyperium/tonic/pull/1204

feat(types): Add gRPC Richer Error Model support (ErrorInfo)

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/debug_info.rs
tonic-types/src/richer_error/std_messages/error_info.rs
tonic-types/src/richer_error/std_messages/mod.rs
tonic-types/src/richer_error/std_messages/prec_failure.rs
tonic-types/src/richer_error/std_messages/quota_failure.rs
tonic-types/src/richer_error/std_messages/retry_info.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1269]. It adds support for the `PreconditionFailure` standard error message type to `tonic-types`.
[#1269]: https://github.com/hyperium/tonic/pull/1269

feat(types): Add gRPC Richer Error Model support (PreconditionFailure)

---

tonic/src/transport/server/tls.rs
tonic/src/transport/service/tls.rs

Previously there were only two options for client authentication – either no authentication or mandatory authentication. With this change, a server can allow for optional authentication with a given root CA certificate and enforce client authentication on a per-request basis.
Refs: #687
Currently, there is no easy way of performing client authentication on a per-request basis with the API provided by `ServerTlsConfig`. This behavior is useful in scenarios like the one described in #687, i.e., when some endpoints should be publicly accessible while others not.
Since `rustls` provides `ClientCertVerifier` with the desired behavior, it only needs to be made accessible from `ServerTlsConfig`. Currently, when the method `client_ca_cert` is called on a `ServerTlsConfig`, it forces mandatory …

feat(tls): add an option for optional TLS client authentication

---

tonic/src/codegen.rs
tonic/src/transport/channel/tls.rs
tonic/src/transport/server/tls.rs

Simplifies the codes.
Removes duplicated tls feature gate and re-exports http crate instead of using wildcard importing.

chore(tonic): Remove duplicate tls feature gate and re-export http crate instead of using wildcard importing

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/mod.rs
tonic-types/src/richer_error/std_messages/resource_info.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1280]. It adds support for the `ResourceInfo` standard error message type to `tonic-types`.
[#1280]: https://github.com/hyperium/tonic/pull/1280

feat(types): Add gRPC Richer Error Model support (ResourceInfo)

---

tonic/src/client/grpc.rs

chore(tonic): Use BoxBody type alias

---

tonic-web/src/layer.rs

Remove unnecessary `Clone` bound in `GrpcWebLayer`

---

examples/Cargo.toml
examples/src/tracing/client.rs

Simplifies examples.
We could use `tracing::instrument` as in the server.

chore(examples): Remove tracing-attributes from dependencies

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/bad_request.rs
tonic-types/src/richer_error/std_messages/debug_info.rs
tonic-types/src/richer_error/std_messages/error_info.rs
tonic-types/src/richer_error/std_messages/help.rs
tonic-types/src/richer_error/std_messages/mod.rs
tonic-types/src/richer_error/std_messages/prec_failure.rs
tonic-types/src/richer_error/std_messages/quota_failure.rs
tonic-types/src/richer_error/std_messages/request_info.rs
tonic-types/src/richer_error/std_messages/resource_info.rs
tonic-types/src/richer_error/std_messages/retry_info.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1282]. It adds support for the `Help` standard error message type to `tonic-types`.
[#1282]: https://github.com/hyperium/tonic/pull/1282

feat(types): Add gRPC Richer Error Model support (Help)

---

tonic-types/src/lib.rs
tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/error_details/vec.rs
tonic-types/src/richer_error/mod.rs
tonic-types/src/richer_error/std_messages/loc_message.rs
tonic-types/src/richer_error/std_messages/mod.rs

The [gRPC Richer Error Model][error-handling] is quite useful to send additional feedback to clients, and is supported by many gRPC libraries in other languages.  
This PR continues the work initiated in [#1068], building on the changes made in [#1293]. It adds support for the `LocalizedMessage` standard error message type to `tonic-types`.  
[#1293]: https://github.com/hyperium/tonic/pull/1293

feat(types): Add gRPC Richer Error Model support (LocalizedMessage)

---

tonic-types/src/lib.rs

We do not need this lint allowing as with [tonic](https://github.com/hyperium/tonic/blob/v0.8.4/tonic/src/request.rs#L388-L390).

chore(types): Remove unnecesarry unreachable_pub lint allowing

---

tonic/src/extensions.rs

Removes redundant reference to reference.

chore(tonic): Remove redundant reference to reference

---

tonic/src/codec/decode.rs
tonic/src/status.rs

This PR fixes how client side streaming is handled on the server side and improves overall source error matching.
Fixes:
- Correctly, detect h2 codes when its wrapped in a hyper error.
- Cancelled requests from the client side during client streaming requests correctly return EOF (`None` from `Streaming::message()`)
Closes #848

fix(codec): Cancelled client streaming handling

---

examples/Cargo.toml
examples/README.md
examples/src/richer-error/client.rs
examples/src/richer-error/client_vec.rs
examples/src/richer-error/server.rs
examples/src/richer-error/server_vec.rs
tonic-types/src/richer_error/error_details/mod.rs

This PR continues the work initiated in [#1068], building on the changes made in [#1295]. It adds examples that show how to implement the richer error model using `tonic-types`.
[#1295]: https://github.com/hyperium/tonic/pull/1295

feat(types): Add gRPC Richer Error Model support (Examples)

---

deny.toml
examples/src/grpc-web/server.rs
tonic-web/src/lib.rs

This fixes `enable` to correctly return a type that implements `NamedService` and improves docs to be more clear.
Fixes #270

fix(web): Fix `enable` and update docs

---

tonic-build/src/prost.rs

`prost-build` has a configuration option called `skip_protoc_run` that prevents running `protoc`. This option is not exposed in `tonic-build`. The option can be used to run `protoc` externally or to use an alternative like `protox`.
This PR adds the option to set `skip_protoc_run` which is passed on to the `prost-build` configuration.

tonic-build: Allow setting skip_protoc_run on the prost Builder

---

tests/integration_tests/Cargo.toml
tests/integration_tests/proto/test.proto
tests/integration_tests/src/lib.rs
tests/integration_tests/tests/max_message_size.rs
tonic-build/src/client.rs
tonic-build/src/server.rs
tonic-health/src/generated/grpc.health.v1.rs
tonic-reflection/src/generated/grpc.reflection.v1alpha.rs
tonic/src/codec/decode.rs
tonic/src/codec/encode.rs
tonic/src/codec/mod.rs
tonic/src/lib.rs

This PR adds new defaults for both client and server max encoding/decoding message size limits. By default, the max message decoding size is `4MB` and the max message encoding size is `usize::MAX`.
This is follow up work from https://github.com/hyperium/tonic/pull/1274
BREAKING: Default max message encoding/decoding limits

feat(core): Default encoding/decoding limits

---

interop/Cargo.toml
interop/src/bin/client.rs
interop/src/bin/server.rs

Simplifies implementations.
As we do not have to read these data asynchronously, we could use std's function.

chore(interop): Remove unnecessary asyncronous file io to read data

---

tests/integration_tests/tests/connect_info.rs
tonic/src/request.rs
tonic/src/transport/server/conn.rs

When bind address to `0.0.0.0`, we need to known which local address the client connect to.
like `remote_addr`.

feat(transport): Add`local_addr` to `Request `

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

All tonic-* crates owned by this repository will now be versioned together to
make it easier to understand which crate matches the core tonic crate version. 
- All crates bumped to 2021 edition
- `tonic-health` and `tonic-reflection` internal protobuf module renamed.
- Default decoding message limit set to `4MiB` by default.
* **build:** Allow Services to be named Result ([#1203](https://github.com/hyperium/tonic/issues/1203)) ([a562a3c](https://github.com/hyperium/tonic/commit/a562a3ce329a38696dfcb0d82b7102d93fb30a5c)), closes [#1156](https://github.com/hyperium/tonic/issues/1156)
* **codec:** Cancelled client streaming handling ([#1315](https://github.com/hyperium/tonic/issues/1315)) ([c8027a1](https://github.com/hyperium/tonic/commit/c8027a1385dd5d3fb6abdce7be49c46a43d4f3c2)), closes …

chore: Prepare `v0.9.0` release

---

.github/workflows/CI.yml

Improves the optimization and the maintenability of the ci.
Moves the process cheking rustfmt to its own job as it does not need to be checked on every platform.

chore: Move rustfmt check to own job

---

.github/workflows/CI.yml

We've had a lot of warnings `Node.js 12 actions are deprecated.` due to aruduino/setup-protoc we've used to setup protoc.  This action does not seem to be actively maintained at the moment.
Replaces arduino/setup-protoc with taiki-e/install-action, which is used in tokio.

chore: Use taiki-e/install-action to setup protoc

---

Cargo.toml
tests/use_arc_self/Cargo.toml
tests/use_arc_self/LICENSE
tests/use_arc_self/build.rs
tests/use_arc_self/proto/test.proto
tests/use_arc_self/src/lib.rs
tonic-build/src/code_gen.rs
tonic-build/src/prost.rs
tonic-build/src/server.rs
tonic-health/src/generated/grpc.health.v1.rs
tonic-reflection/src/generated/grpc.reflection.v1alpha.rs

This implements an option to emit `Arc<Self>` instead of `&self` in server traits. This enables implementor to reference `Self` data for indefinite duration, which may be useful for streaming requests.
Fixes: #1351
I have a few comments about this:
This impl required me to generate a new `inner_arg` token stream for each method, because I could not find a way to easily coerce between `Arc<T>` and `&T` in a generic way that does not conflict with ambiguous function names.
Tests are very minimal, if this feature looks good otherwise, I'll add more.

feat(build): Optionally to emit `Arc<Self>` as server receiver

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/server/mod.rs

Old links were broken. https://github.com/hyperium/tonic/issues/1365
Updated links.

fixing broken links for window size and max concurrent streams

---

deny.toml

Improves development experiences when running cargo-deny checking locally.
Sets all-features option true in deny config instead of using `--all-features` command line argument.

chore: Set all-features option true in deny config

---

interop/Cargo.toml

Updates to [`strum` 0.25](https://github.com/Peternator7/strum/blob/2bcf86d0ca5cb5c733031d41aacce881643433da/CHANGELOG.md#L3).
Updates to use it.

chore(interop): Update to strum 0.25

---

tonic/Cargo.toml
tonic/src/client/grpc.rs
tonic/src/server/grpc.rs
tonic/src/transport/server/incoming.rs

Continues #1364.
Reduces `futures-util` in favor of `tokio-stream`.

chore: Reduce futures-util in favor of tokio-stream

---

interop/Cargo.toml
interop/src/client.rs
interop/src/server.rs

Continuing #1421.
This removes `futures-core` and `futures-util` from `interop`.

chore(interop): Replace futures crates with tokio-stream

---

examples/Cargo.toml
examples/src/hyper_warp/server.rs
examples/src/hyper_warp_multiplex/server.rs

Continuing from #1438.
Removes `futures-util` in examples. Converts `Future` manually and uses `either` crate where `futures_util::future::Either` used.

chore(examples): Remove futures-util

---

examples/routeguide-tutorial.md

Reduces futres crates.
Replaces `futures-core` and `futures-util` with `tokio-stream` in the document.

chore(doc): Replace futures crates with tokio-stream

---

tonic/src/transport/server/mod.rs

This adds the [`http2_max_pending_accept_reset_streams`](https://docs.rs/hyper/latest/hyper/server/conn/struct.Http.html#method.http2_max_pending_accept_reset_streams) property to the server, to configure the allowed number of reset streams pending accept.
In [Qdrant](https://github.com/qdrant/qdrant) we're trying to use hundreds of streams over HTTP2, all having a good chance to be dropped/reset. This makes it very easy to reach the default limit of [20](https://docs.rs/h2/latest/h2/server/struct.Builder.html#method.max_pending_accept_reset_streams) reset streams, causing internal connection errors, causing cluster consensus problems in production.
We'd like to greatly increase this limit for our internal cluster communication to prevent triggering the `GOAWAY/ENHANCE_YOUR_CALM` error. …

tonic: add hyper's `http2_max_pending_accept_reset_streams` to server

---

tests/compression/Cargo.toml
tests/compression/src/bidirectional_stream.rs
tests/compression/src/client_stream.rs
tests/compression/src/compressing_request.rs
tests/compression/src/compressing_response.rs
tests/compression/src/lib.rs
tests/compression/src/server_stream.rs
tests/compression/src/util.rs
tests/integration_tests/Cargo.toml
tests/integration_tests/tests/client_layer.rs
tests/integration_tests/tests/extensions.rs
tests/integration_tests/tests/interceptor.rs
tests/integration_tests/tests/max_message_size.rs
tests/integration_tests/tests/origin.rs
tests/integration_tests/tests/status.rs
tests/integration_tests/tests/streams.rs
tests/use_arc_self/Cargo.toml
tests/use_arc_self/src/lib.rs

Continuing of #1444.
Reduces futures crates in tests.

chore(tests): Reduce futures crates

---

.github/workflows/CI.yml

Fixes unnecessary doc tests being executed and the redundant ci definitions, and make the doc test fail when their errors are thrown. I think we can remove doc test on test crates (they might throw unnecessary document warnings or errors as well. For example, [some warnings](https://github.com/hyperium/tonic/actions/runs/5754277946/job/15599233527#step:6:64) have been appeared).
- Changes the doc tests to be run only against those which are aimed to be published.
- Makes the doc test fail when they throw warnings.
- Moves doc test to the msrv job as the most of the test process is same.

chore: Improve cargo doc ci

---

.github/workflows/CI.yml

Uses `taiki-e/install-action` to setup `cargo-hack`. This action is maintained by the same author of `cargo-hack`.

chore: Use taiki-e/install-action to setup cargo-hack

---

deny.toml

`tokio` bumped its MSRV to `1.63` and changed to use `socket2` 0.5, which bumped its MSRV to `1.63` as well. As `hyper`'s MSRV is 1.56, `tonic` became to depend on multiple versions of `socket2`. This pull request allows to use them to fix ci.
Adds `socket2` to cargo deny skip-tree config.

chore: Add socket2 to cargo deny skip-tree config

---

tonic/Cargo.toml
tonic/src/codec/encode.rs
tonic/src/codegen.rs
tonic/src/server/grpc.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/service/add_origin.rs
tonic/src/transport/service/connection.rs
tonic/src/transport/service/connector.rs
tonic/src/transport/service/executor.rs

Continuing of reducing futures crates.
Replaces them with alternative implementations.

chore(tonic): Reduce futures-util

---

tonic-reflection/Cargo.toml
tonic-reflection/tests/server.rs

Continuing of reducing futures crates.
Removes `futures-util` from `tonic-reflection` entirely.

chore(reflection): Remove futures-util

---

tests/integration_tests/Cargo.toml
tests/integration_tests/src/lib.rs
tests/integration_tests/tests/client_layer.rs
tests/integration_tests/tests/connect_info.rs
tests/integration_tests/tests/connection.rs
tests/integration_tests/tests/extensions.rs
tests/integration_tests/tests/interceptor.rs
tests/integration_tests/tests/origin.rs
tests/integration_tests/tests/status.rs
tests/integration_tests/tests/streams.rs
tests/integration_tests/tests/user_agent.rs

Continuing of reducing futures crates.
Removes `futures-util` from tests entirely.

chore(tests): Remove futures-util

---

.github/workflows/CI.yml

Improves readability and maintainability.
- Defines `RUSTFLAGS` environment variables at one place which are aimed to use every jobs.
- Moves `QUICKCHECK_TESTS` environment variable at the place to be used.
- Removes redundant matrix variable `rust`, which is only `stable`.
- Reorders steps for the uniform order.
- Updates deprecated cargo option `--all` to `--workspace`.
- Adds msrv comment to be easily found by command like grep.
- Makes `check` and `msrv` job next to each other as they have similar structure.

chore: Refactor ci

---

tests/default_stubs/Cargo.toml
tests/default_stubs/src/lib.rs

Reduces `futures` crate.
Uses `tokio-stream` instead of `futures`.

chore(tests): Remove futures

---

.github/workflows/CI.yml
README.md
deny.toml

`tonic-build` now depends on `indexmap 2.0.0` (whose MSRV is 1.64) via `prost-build`.

chore: Bump msrv to 1.64

---

examples/src/tls/client.rs
examples/src/tls_client_auth/client.rs

Fixes examples errors.
Uses `https` scheme when using tls.

fix(examples): Use https scheme when using tls

---

tonic/src/transport/server/mod.rs

Some methods on the [`Router`] utilise the TCP configuration of the [`Server`], and others don't. 
It's fairly obvious why when looking at the generic bounds, but we were using `serve_with_incoming()` with a `TcpListenerStream` (which seems to be [not uncommon]) and the author hadn't made the mental leap that this would cause `TCP_NODELAY` to be disabled / default discarded.
I nearly didn't open this, because it's somewhat obvious in hindsight, but a small docs tweak might save some others a bit of confusion.
[not uncommon]: https://github.com/search?q=repo%3Ahyperium%2Ftonic%20TcpListenerStream&type=code
[`Router`]: https://docs.rs/tonic/0.9.2/tonic/transport/server/struct.Router.html#method.serve_with_incoming
[`Server`]: https://docs.rs/tonic/0.9.2/tonic/transport/server/struct.Server.h …

docs: discarded server TCP connection config

---

examples/Cargo.toml
examples/src/cancellation/client.rs
examples/src/cancellation/server.rs
examples/src/timeout/client.rs

There are some valid usecases for being notified of request cancellation and executing clean up logic on client cancellation.
This can be easily done with server streaming and bidi streaming, but there doesn't seem to be a straightforward approach for unary RPCs.
Creating a new task for unary requests (like in server/bidi streaming requests), having the unary request' future await on this new task with a CancellationToken drop guard.
Under the assumption that request futures are dropped when client cancels the request, this will notify the task through the drop guard's drop logic

chore(examples): Add `cancellation` example

---

tonic/Cargo.toml

Turns off a unused feature.
Enables `tokio`'s `macros` feature only when it is used.

chore(tonic): Move tokio macros feature behind tls feature

---

tests/compression/Cargo.toml
tests/compression/src/util.rs
tonic-web/Cargo.toml
tonic-web/src/call.rs
tonic-web/src/client.rs
tonic-web/src/service.rs
tonic/Cargo.toml
tonic/src/client/grpc.rs
tonic/src/codec/decode.rs
tonic/src/codec/encode.rs
tonic/src/codec/prost.rs
tonic/src/server/grpc.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/server/recover_error.rs
tonic/src/transport/service/grpc_timeout.rs
tonic/src/transport/service/router.rs

Completes of removing futures crates.
- Replaces `futures_{core, util}::ready` with `std::task::ready`, which was stabilized at Rust 1.64.
- Uses `pin_utils` crate directly instead of via `futures_util`. (When `tonic`'s MSRV be bumped to Rust `1.68` in the future, `std::pin::pin` can be used.)

chore: Remove futures crates

---

tonic-reflection/src/generated/grpc_reflection_v1alpha.rs
tonic-types/src/generated/google_rpc.rs

Reflects `prost-build`'s changes caused by https://github.com/tokio-rs/prost/pull/851.
Updates generated codes.

chore: Update generated code

---

tonic/Cargo.toml
tonic/src/transport/service/tls.rs

Small refactorings of `tonic`'s tls config.
- Removes `rustls` crate from dependencies as it is not used.
- Updates to `rustls-native-certs` 0.6.3 from 0.6.1 and use its `AsRef<[u8]>` for `Certificate`.
- Uses `AsRef<u8>` for `tonic`'s `Certificate` struct instead of slice syntax.

chore(tls): Small refactoring

---

CHANGELOG.md
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

* **web:** Buffer incomplete messages ([#1528](https://github.com/hyperium/tonic/issues/1528)) ([fe6f8d9](https://github.com/hyperium/tonic/commit/fe6f8d9b4953a266eb32945a67edce9558bd05b3))

chore: Prepare `0.10.1` release

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

* **web:** Client decoding incomplete buffer bug ([#1540](https://github.com/hyperium/tonic/issues/1540)) ([83e363a](https://github.com/hyperium/tonic/commit/83e363ace6cbe20ccc2efbe1eb10a4236e4b8065))

chore: Prepare `0.10.2` release

---

examples/src/mock/mock.rs
interop/src/client.rs
interop/src/server.rs
tests/compression/src/bidirectional_stream.rs
tests/compression/src/client_stream.rs
tests/compression/src/compressing_request.rs
tests/compression/src/compressing_response.rs
tests/compression/src/server_stream.rs
tests/integration_tests/tests/max_message_size.rs
tests/integration_tests/tests/routes_builder.rs
tonic-reflection/tests/server.rs

Refactoring.
Refactors the use of `tokio-stream`.

chore: Refactor use of tokio-stream

---

.github/workflows/CI.yml

`hecrj/setup-rust-action@v2` is reelased.
https://github.com/hecrj/setup-rust-action/releases/tag/v2.0.0
Updates to `hecrj/setup-rust-action@v2` from version 1.

chore: Update to hecrj/setup-rust-action@v2

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/service/connector.rs
tonic/src/transport/service/discover.rs
tonic/src/transport/service/mod.rs

Simplifies implementations.
Removes the redundant helper functions which construct Connector.

chore: Remove redundant helper constructor

---

tonic/src/codec/encode.rs

A small refactoring on codec.
`tokio-stream` provides a method to convert stream to fused one. Uses it instead of porting `futures-util`'s one.

chore(codec): Replace tonic::codec::encode::fuse with tokio-stream

---

interop/src/server.rs
tests/integration_tests/tests/extensions.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs

Removes old API.
`NamedService` has been re-exported in transport module for the historical reason. The re-exporting could be removed. As `deprecated` does not handle re-export, the deprecation should be at the comment.

chore(transport): Deprecate re-exported NamedService

---

tonic/src/request.rs
tonic/src/transport/mod.rs
tonic/src/transport/tls.rs

#1516
Deprecates [`Request::local_addr`](https://docs.rs/tonic/0.10.0/tonic/struct.Request.html#method.local_addr), [`Request::remote_addr`](https://docs.rs/tonic/0.10.0/tonic/struct.Request.html#method.remote_addr) and [`Request::peer_certs`](https://docs.rs/tonic/0.10.0/tonic/struct.Request.html#method.peer_certs) when they only return `None`.

chore(tonic): Deprecate API when they only return None

---

tonic/src/request.rs
tonic/src/transport/mod.rs
tonic/src/transport/tls.rs

Continues  #1520 and resolves #1516.
> [!WARNING] 
> This proposal includes breaking changes.
Removes APIs when they only return `None`.

chore(tonic): Remove API when they only return None

---

tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs

Continues  #1521.
> [!warning]
> This proposal includes breaking changes.
Removes deprecated re-exported `NamedService`.

chore(lib): Remove re-exported NamedService

---

.github/workflows/CI.yml
README.md

`home` 0.5.9, which `tonic` depends on via `prost-build`, requires Rust 1.70.

chore: Bump msrv to 1.70

---

tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs

`tonic-reflection` cannot be used in certain environments eg. wasm, due to a dependency on the `tokio` runtime.
The `tokio` runtime is only used in `tonic_reflection::server`, and so it makes sense to feature-gate this module and make it a default feature, for backwards compatibility.
This PR makes it possible to use the `tonic_reflection::pb` module without having to build `tokio`.
This is useful for eg. wasm reflection clients.

tonic-reflection: feature-gate server impl

---

tonic-build/src/prost.rs

In my codebase I have files generated by prost and by tonic. I noticed that rust-analyzer was working fine with files generated by prost but not with files generated by tonic. 
I found out that rust-analyzer doesn't like when a generated file is included with relative path. It only works with absolute path (i.g. when using the `OUT_DIR` env variable).
I also found out that tonic always calls `prost_build::Config.out_dir`, which causes prost to always generate includes with relative paths.
My solution was to avoid setting the `out_dir` in prost when unnecessary.

Repair rust-analyzer for tonic files

---

tonic/src/transport/channel/endpoint.rs

Currently connect_with_connector_lazy doesn't respect connection timeouts. This means that if you have a misbehaving or unresponsive server, a request that's connecting lazily with a custom connector can hang for the client without timing out. This commit adds the timeout to the custom connector if it has been set on the endpoint, bringing the behaviour in line with other connect methods.
This brings the behaviour of `connect_with_connector_lazy` in line with the other connect methods that respect the connection time set on the Endpoint.
This solves instances where users set a connection time out on an endpoint, but use a custom connector to connect lazily. If the server fails to respond to the connection request at all then the connection attempt (and request) will hang without ever …

Add connection timeout to connect_with_connector_lazy

---

examples/helloworld-tutorial.md

Fix Clippy lints:
warning: useless conversion to the same type: `std::string::String`

Update helloworld-tutorial.md - Fix Clippy lints

---

Cargo.toml
deny.toml
tonic/Cargo.toml
tonic/src/transport/channel/tls.rs
tonic/src/transport/service/connector.rs
tonic/src/transport/service/tls.rs

chore(tls): Update to rustls 0.22.0

---

tonic/Cargo.toml
tonic/src/client/grpc.rs
tonic/src/codec/prost.rs
tonic/src/server/grpc.rs
tonic/src/transport/server/incoming.rs

[`std::pin::pin`](https://doc.rust-lang.org/std/pin/macro.pin.html) can be used now as `tonic`'s MSRV is updated to 1.70.

chore: Replace tokio::pin with std::pin::pin

---

tonic/src/transport/service/connector.rs

The `tls` field of `Connector` is unused when `tls` feature is not used.
Removes `tls` field when `tls` feature is not used.

chore(tls): Remove unused tls field when tls feature is not used

---

.github/workflows/CI.yml

`actions/checkout@v4` is released.
https://github.com/actions/checkout/releases/tag/v4.0.0
Updates to `actions/checkout@v4` from version 3.

chore: Update to actions/checkout@v4

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/tls.rs
tonic/src/transport/service/connector.rs
tonic/src/transport/service/tls.rs

Sometimes servers are secured with tls and speak gRPC, but don't perform ALPN protocol negotation. Most other gRPC implementations out there, as far as I can tell will just assume that the remote server is speaking h2 if there is ALPN. Tonic is strict in this regard. This patch takes the conservative approach of allowing users to opt into assuming that the remote server is running h2. A more aggressive patch in the future might be to invert the default.
This patch allows users to connect to gRPC services over TLS that don't use ALPN. The rest of the ecosystem seems to support this. See https://github.com/hyperium/tonic/issues/1427.
The patch allows users to opt into this behavior either by configuring the TlsClientConfig or, when using `tls-roots-common` to configure the endpoint to opt …

feat(transport): opt into TLS with servers without ALPN

---

examples/src/tls_rustls/client.rs
interop/src/server.rs

chore: Apply small refactoring

---

.github/workflows/CI.yml

Improves ci by using `cargo-hack`'s new feature.
Uses `cargo-hack`'s more powerful `--no-private` option ([doc](https://github.com/taiki-e/cargo-hack/blob/v0.6.0/CHANGELOG.md#060---2023-08-28)) to avoid checking local crates, which is introduced recently.

chore: Use cargo-hack --no-private option instread of --ignore-private

---

tonic/src/extensions.rs

This exposes `Extensions::from_http` to allow user to write more efficient tower's Service instead of using Interceptor as it doesn't allow to customize Response

Expose Extensions::from_http to user

---

tonic-build/src/lib.rs

Single character spelling fix in lib.rs in tonic-build

build: fix typo in documentation

---

interop/Cargo.toml

chore(interop): Update to strum 0.26

---

tonic/src/transport/channel/endpoint.rs

Simplifies implementations.
`hyper` has connection timeout mechanism. `tonic` could use it instead of `hyper-timeout`'s connection when using `hyper` connector. As `connect_with_connector` does not assume only `hyper`'s connection, `hyper-timeout` cannot be removed at this point.

chore(transport): Use hyper timeout feature

---

tests/root-crate-path/Cargo.toml
tonic/Cargo.toml

Updates deprecated manifest field style, which will be removed in 2024 edition.
https://github.com/rust-lang/cargo/pull/13804

chore: Update deprecated manifest style

---

tonic/Cargo.toml

`async-stream` is now used in `transport` feature.
Moves `async-stream` crate to `transport` section.

chore(tonic): Move async-stream crate to transport section

---

tonic/src/codec/encode.rs

Replaces deprecated numeric API with primitive one.
https://doc.rust-lang.org/std/u32/index.html

chore: Replace deprecated numeric api with primitive one

---

tonic-build/README.md

The GitHub page will hightlight the `wrong` grammar in markdown, it causing unnecessary visual attraction
Add double quotes in yaml block, it also meets the requirements of cargo.

docs(tonic-build): Fix wrong hightlight

---

tonic/src/codec/buffer.rs

The internal buffers within the codec `EncodeBuf`/`DecodeBuf` implementations contain what looks like more optimized implementations of `BufMut`/`Buf`, which we can take advantage of.
For `DecodeBuf`, we can reuse `BytesMut`'s `copy_to_bytes` implementation, we just need to also update the length.
For `EncodeBuf`, we should be able to just reuse all of `BytesMut`'s implementation of `BufMut`, which looks a bit simpler than the default implementation.
Out of curiosity, I tried running the benchmarks:
**Before:**
```
test chunk_size_100   ... bench:         514 ns/iter (+/- 34) = 1955 MB/s
test chunk_size_1005  ... bench:         340 ns/iter (+/- 29) = 2955 MB/s
test chunk_size_500   ... bench:         378 ns/iter (+/- 22) = 2658 MB/s
test message_count_1  ... bench:         317 ns/iter …
```

use internal buffer's Buf impl for codec buffers

---

.github/workflows/CI.yml

Upgrading to hyper>=1 will reqiure that we upgrade axum to >= 0.7. Bumping nightly is required to support axum >= 0.7 on nightly, since it uses features not stabilized before this date. This is in turn reqiured to run `cargo udeps` against tonic and associated crates.

Bump nightly to 2024-04-16

---

tonic/src/codec/encode.rs
tonic/src/transport/server/recover_error.rs

Provides the `Body` stream's size hint.
Implements `Body::size_hint` for custom body types. It is intentional that this is not added to test code.

feat: Implement http_body::Body::size_hint for custom body

---

tonic/src/request.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/conn.rs
tonic/src/transport/tls.rs

Although `Certificate` is for PEM encoded certificate, it is used by `Request::peer_certs`'s return type, which is DER encoded certificate.
Adds `CertificateDer` type and changes `Request::peer_certs` to use it.
This is a breaking change.

feat(tls): Use rustls_pki_types::CertificateDer to describe DER encoded certificate

---

.github/workflows/CI.yml

Removes the effects from `dev-dependencies` to MSRV, and makes easier to specify public crates for checking.
Uses `cargo-no-dev-deps` to check msrv.

chore: Use cargo-no-dev-deps to check msrv

---

tonic/src/status.rs

Refactors the implementation.
Refactors the procedure to convert `Status` to `http::Response`.

chore: Refactor convert Status to http::Response

---

tonic/src/server/grpc.rs

Reduces duplicated codes.
Uses `t!` macro.

chore: Use t macro instead of reimplementing

---

tonic/src/server/grpc.rs
tonic/src/service/interceptor.rs
tonic/src/status.rs

Follows to the naming convention.
https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv

chore: Rename Status to_http method to into_http

---

deny.toml

Removes resolved cargo-deny skip-tree.

chore: Remove resolved cargo-deny skip-tree

---

tonic/src/extensions.rs

feat: Relax GrpcMethod lifetime

---

tonic/Cargo.toml
tonic/src/service/mod.rs
tonic/src/service/router.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/service/mod.rs

Allows users to use the service router independent from transport feature.

feat(transport): Make service router independent from transport

---

tests/integration_tests/tests/http2_keep_alive.rs
tonic/src/transport/server/mod.rs

As described in this issue: https://github.com/hyperium/tonic/issues/1725 the recent upgrade to hyper 1 has broken services that use http2_keepalive_interval. This was due to a missing timer, resulting in panics with the message `You must supply a timer.` See here: https://github.com/hyperium/hyper/blob/master/src/common/time.rs#L36
This solution adds in a timer to the server via this method: https://docs.rs/hyper-util/0.1.5/hyper_util/server/conn/auto/struct.Http2Builder.html#method.timer
The timer is a standard tokio timer: https://docs.rs/hyper-util/0.1.5/hyper_util/rt/tokio/struct.TokioTimer.html
Fixes https://github.com/hyperium/tonic/issues/1725

Add timer to hyper server for http2_keepalive_interval

---

tests/integration_tests/tests/http2_keep_alive.rs
tonic/src/transport/service/connection.rs

https://github.com/hyperium/tonic/pull/1726 fixed http2_keepalive on the server side, but panics were still present when using http2_keepalive on the client side. 
Add the necessary timer to the SharedExec when constructing it via `tonic::transport::service::Connection`.

Fix http2_keepalive panics on the client side

---

tonic/src/transport/server/mod.rs

Uses `hyper_util::service::TowerToHyperService` instead of defining the own version with change.

chore(transport): Use hyper_util::service::TowerToHyperService

---

tonic/src/transport/channel/tls.rs
tonic/src/transport/service/connector.rs
tonic/src/transport/service/tls.rs

feat(tls): Add ability to add multiple ca certificates

---

tonic-build/src/server.rs
tonic-health/src/generated/grpc_health_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1alpha.rs
tonic-web/src/service.rs
tonic/src/client/grpc.rs
tonic/src/metadata/mod.rs
tonic/src/server/grpc.rs
tonic/src/service/router.rs
tonic/src/status.rs

This is continue for: https://github.com/hyperium/tonic/pull/1648

Add a `GRPC_CONTENT_TYPE` for "application/grpc".

---

tonic-build/src/server.rs
tonic-health/src/generated/grpc_health_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1alpha.rs

Removes a redundant clone in the `tower-service::Service::call()` implementation, and reduces the amount of generated code. Does not break any user facing API.
Don't know how much the removed clone matters in practice. Perhaps it gets optimized away during compilation regardless 🙈

chore(codegen): Deprecate _Inner<T>.

---

tonic-types/src/richer_error/error_details/mod.rs
tonic-types/src/richer_error/mod.rs

Useful when converting custom errors to a `tonic_types::Status`.

`impl From<ErrorDetails> for Vec<Any>`

---

tonic/Cargo.toml

`hyper-util` 0.1.4 has already required `socket2` 0.5.

chore: Remove socket2 version range config

---

examples/src/tls_rustls/server.rs
tonic/src/codec/decode.rs
tonic/src/service/router.rs
tonic/src/transport/channel/service/connection.rs
tonic/src/transport/channel/service/connector.rs

Applies miscellaneous refactoring.

chore: Small refactoring

---

tonic/Cargo.toml
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/service/connector.rs
tonic/src/transport/channel/service/tls.rs
tonic/src/transport/channel/tls.rs

Adds ability to add CA certificates and removes `tls-webpki-roots` and `tls-roots` features.

feat(tls): Remove tls roots implicit configuration

---

tonic-build/src/lib.rs
tonic-health/src/lib.rs
tonic-health/src/server.rs
tonic-reflection/src/lib.rs
tonic/src/codec/compression.rs
tonic/src/codec/mod.rs
tonic/src/lib.rs
tonic/src/request.rs
tonic/src/response.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/channel/tls.rs
tonic/src/transport/mod.rs
tonic/src/transport/server/conn.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/server/unix.rs

Uses `doc_auto_cfg` instead of manual implementation.

chore(doc): Enable doc_auto_cfg

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/tls.rs

These value clones seem not to be needed.

chore(channel): Reduce unnecessary value clone

---

tonic/src/transport/server/mod.rs
tonic/src/transport/server/service/tls.rs

This reexport seems to be redundant.

chore(tls): Remove redundant reexport of TlsStream

---

tonic/Cargo.toml
tonic/src/service/router.rs

This can be implemented by using tower's map_request.

chore(router): Remove wrapper type for axum router

---

tests/integration_tests/tests/status.rs
tonic/src/codec/encode.rs

#1423 introduced logic to buffer multiple ready messages in order to amortize the cost of sends to the underlying transport. This also introduced a change in behavior for tonic in the following scenario:
A stream of ready messages less than the yield threshold is trailed by a status. Previously the ready messages would all have been yielded from the stream and sent, followed by the status. After the change was introduced the status is yielded from the stream and sent but the accumulated ready messages in the buffer are never sent out.
This change adjusts the logic to restore the previous behavior while still retaining the amoritization benefits. Namely it flushes the accumulated ready messages prior to yielding the status ensuring they are sent out from the stream in the order they are …

fix(tonic): flush accumulated ready messages when status received

---

tonic/src/codec/compression.rs

Alternative approach to #1727, enable callers to influence compression encoding priority. Also changes the default order so that `Zstd` comes before `Gzip` if enabled (which happens when the `zstd` Cargo feature is explicitly enabled).
Implement an internal array while avoiding making changes to existing public API.
cc @CapCap

Make compression encoding configuration more malleable

---

tonic/src/codec/compression.rs
tonic/src/server/grpc.rs

This compression encodings list seems not to be needed to be a function.

chore(codec): Make encodings list const value

---

tonic/src/codec/compression.rs

Simplifies EnabledCompressionEncodings's into_accept_encoding_header_value method.

chore(codec): Simplify EnabledCompressionEncodings into_accept_encoding_header_value method

---

tonic/src/codec/compression.rs

Reduces duplicate similar implementations for the similar purpose.

chore(codec): Use as_str method to implement display for CompressionEncoding

---

examples/src/h2c/server.rs
tonic/src/body.rs

Providing the way to create body gives greater flexibility. This change eliminates the need to use axum's features in the case of h2c example.

feat: Make boxed function public

---

tonic/src/codec/compression.rs

Makes error in the case when not utf8 value is in the compression encoding.

feat(codec): Make error when not utf8 value in compression encoding

---

examples/src/authentication/server.rs
examples/src/multiplex/server.rs
examples/src/tls/server.rs
examples/src/tls_client_auth/server.rs
examples/src/tls_rustls/server.rs
examples/src/tower/server.rs
interop/src/server.rs

Resolves clippy warnings and improves codes consistency.

chore: Replace unit struct with ordinary struct

---

examples/Cargo.toml
interop/Cargo.toml
tests/ambiguous_methods/Cargo.toml
tests/compression/Cargo.toml
tests/default_stubs/Cargo.toml
tests/disable_comments/Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/included_service/Cargo.toml
tests/integration_tests/Cargo.toml
tests/root-crate-path/Cargo.toml
tests/same_name/Cargo.toml
tests/service_named_result/Cargo.toml
tests/service_named_service/Cargo.toml
tests/stream_conflict/Cargo.toml
tests/use_arc_self/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tests/wellknown/Cargo.toml
tonic-build/Cargo.toml
tonic-health/Cargo.toml
tonic-health/src/generated/grpc_health_v1.rs
tonic-reflection/Cargo.toml
tonic-types/Cargo.toml
tonic-types/src/generated/google_rpc.rs
tonic-web/tests/integration/Cargo.toml
tonic/Cargo.toml

BREAKING CHANGE: update prost version to v0.13.0

feat: update `prost` to `v0.13.0`

---

CHANGELOG.md
examples/helloworld-tutorial.md
examples/routeguide-tutorial.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

This breaking release updates tonic to the hyper `1.0` ecosystem and also updates
to prost `v0.13.0`.
* **build:** Custom codecs for generated code ([#1599](https://github.com/hyperium/tonic/issues/1599)) ([18a2b30](https://github.com/hyperium/tonic/commit/18a2b30922460be02829706cf9dd0cd1ec6a19c1))
* **channel:** Make channel feature additive ([#1574](https://github.com/hyperium/tonic/issues/1574)) ([b947e1a](https://github.com/hyperium/tonic/commit/b947e1ac0727ceb0a0267a30854ada4ba18931db))
* **codec:** Make error when not utf8 value in compression encoding ([#1768](https://github.com/hyperium/tonic/issues/1768)) ([f8e1f87](https://github.com/hyperium/tonic/commit/f8e1f87eb862676147fd6215b58c9090d259104d))
* Implement http_body::Body::size_hint for custom body …

chore: release v0.12.0

---

examples/routeguide-tutorial.md
examples/src/routeguide/server.rs

Removes clone of the value which implements copy trait.

chore(examples): Remove clone on copy value

---

tonic/src/transport/server/incoming.rs
tonic/src/transport/server/service/tls.rs

Removes unnecessary Connected trait bounds.

chore(server): Remove unnecessary Connected trait bound

---

tonic/src/codec/compression.rs

Removes redundant trim which are called duplicately for the first and last parts.

chore(codec): Remove redundant trim

---

examples/helloworld-tutorial.md
examples/routeguide-tutorial.md

The `cargo.toml` in the hello world and route guide tutorials uses `prost = "0.12"`. This issue is mentioned in issue [#765](https://github.com/hyperium/tonic/issues/765).
Change `prost = "0.12` to `prost = 0.13`.

fix to hello world and route guide tutorials

---

tonic/src/transport/server/service/tls.rs

chore(server): Remove unnecessary bound from TlsAcceptor::accept

---

tonic/src/transport/server/service/io.rs

This trait bound is satisfied by the IO bound.

chore(server): Remove unnecessary trait bound from ServerIo::connect_info

---

tonic-reflection/src/server/mod.rs
tonic-reflection/src/server/v1.rs

To simplify API verification, this is a prepatory change to shift around the v1 support to allow for a cleaner v1alpha reintroduction.
* Created a multi-file version of the server.rs module
* Added mod.rs containing the base `Error` with associated imports / exports
* Added v1.rs containing the v1 version of the reflection server
The current `v1` reflection API support is lacking in various existing tools (like *Postman* and *Kreya*).
From feedback in https://github.com/hyperium/tonic/pull/1787, we should split the change into multiple PRs.
This change splits the server module to enable us to re-add the `v1alpha` support in a later PR a cleaner fashion.

tonic-reflection: Restructure module to prep reintroducing v1alpha

---

tonic/src/transport/channel/service/executor.rs

Uses hyper_util::rt::TokioExecutor instead of defining the own type.

chore(channel): Use hyper_util::rt::TokioExecutor

---

interop/build.rs
tonic-build/src/prost.rs
tonic-web/tests/integration/build.rs

I was looking through and debugging some services and noticed that the `println!()` statements in the `tonic-build` crate were not correctly formatted.
Example 1: https://github.com/hyperium/tonic/blob/255a885d316392a0135fa810ecfd5ae87135a329/tonic-build/src/prost.rs#L651
Example 2:
https://github.com/hyperium/tonic/blob/255a885d316392a0135fa810ecfd5ae87135a329/tonic-build/src/prost.rs#L658
They all have a single `:` when they should have 2 as shown in the cargo book:
https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed
Just added the extra `:`, did a full workspace search to ensure I got all of them :+1:
---
If there's anything else you'd like me to do to properly follow any requirements please let met know :smile:

fix(tonic-build): cargo build script outputs are not functional

---

tonic/src/lib.rs
tonic/src/status.rs
tonic/src/transport/mod.rs
tonic/src/transport/service/grpc_timeout.rs

By moving the TimeoutExpired type from the transport module to the the tonic engine proper, the type is made available to other transport implementations and tonic can be built without the "server" feature while still returning a Status indicating the timeout.
Alternative transport implementations can use the type, now that it is moved, when they want the tonic Status error handling to recognize the error as having been triggered by a timeout in the transport logic. The tonic Status error will have a code of Cancelled with a message of "Timeout expired".
There is already a test for this:
cargo test picks_server_timeout_if_thats_sorter
which worked the original way and contines to work; but now a new transport implementation can get the same behavior.
Addresses #1825.

chore(tonic): Move TimeoutExpired out of transport

---

deny.toml

cargo deny failed in https://github.com/hyperium/tonic/actions/runs/10198566819/job/28213729309?pr=1829 due to the 2-clause BSD license which is used by the zerocopy crate (via rand -> rand_chacha -> ppv-lite86).

chore: Allow 2-clause BSD licenses

---

tests/integration_tests/Cargo.toml
tests/integration_tests/tests/extensions.rs

chore(test): Use http crate directly

---

.github/workflows/CI.yml

Allows `workspace-duplicates` which is introduced at `cargo-deny` [0.15](https://github.com/EmbarkStudios/cargo-deny/releases/tag/0.15.0), and `BSD-2-Clause` which is newly pulled in dependencies.

chore: Update to EmbarkStudios/cargo-deny-action@v2

---

tests/integration_tests/tests/http2_max_header_list_size.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/service/connection.rs

There is a bug such that if the client sends a response with a header value that exceeds the max_header_list_size, then RPCs just hang (#1834). When tonic upgraded to hyper 1, it picked up [hyper#3622] which changed the default from 16MiB to 16KiB for this configuration value. Error messages in gRPC use headers. That means that services which ever sent error messages in excess of 16KiB (including in their error details!) will just hang.
This commit adds the ability for the client to configure this value to something larger (perhaps the old default of 16MiB) to mitigate the above-referenced bug. 
[hyper#3622]: https://github.com/hyperium/hyper/pull/3622

transport: allow setting max_header_list_size

---

.github/workflows/CI.yml

Checking on a single platform would be sufficient as there is not platform specific dependency.

chore: Check udeps only on ubuntu

---

tonic/src/transport/server/mod.rs

Considering the intent of the process, it seems that mapping hyper's body should be processed with converting to hyper service.

chore(server): Refactor converting to hyper service

---

tonic/src/codec/compression.rs

Seems not to be needed to use fully qualified syntax.

chore(codec): Use method chain style

---

deny.toml

BSD-2-Clause seems not to be needed.

chore: Remove BSD-2-Clause from cargo-deny config

---

tonic/src/codec/prost.rs

Replaces unit struct with ordinary struct.

chore(test): Replace unit struct with ordinary struct

---

tonic/src/transport/server/mod.rs

This can be obtained from Routes directly.

feat(server): Deprecate method to convert router into axum router

---

tonic/src/service/router.rs
tonic/src/transport/server/mod.rs

To describe what the method does more clearly, I would suppose that `Routes::into_axum_router` is more appropriate method name.

feat(router): Rename Routes::into_router with into_axum_router

---

tonic/src/service/router.rs

Implements `From<axum::Router>` for `Routes`. This is useful when users want to route any services with axum's router in the easy way.

feat(router): Implement from axum::Router for Routes

---

tonic/src/service/router.rs

Adds missing unimplemented fallback routing when constructing `Routes` via `Routes::default` or `RoutesBuilder`.

feat(router): Add missing unimplemented fallback to RoutesBuilder

---

tonic-types/src/richer_error/std_messages/retry_info.rs
tonic/src/codec/mod.rs

chore: fix some comments

---

tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs

On FreeBSD, accept can fail with `ECONNABORTED`, which means that *"A connection arrived, but it was closed while	 waiting on the listen queue."* (see [`man 2 accept`](https://man.freebsd.org/cgi/man.cgi?accept(2) )), which [is in line with POSIX](https://pubs.opengroup.org/onlinepubs/9799919799/functions/accept.html).
Without this patch, a server built without the `tls` feature exits returning 0 in case of an aborted connection, which makes it vulnerable not only to intentional denial of service, but also to unintentional crashes, e.g., by haproxy TCP health checks.
The problem can be reproduced on any FreeBSD system by running the tonic "helloworld" example (when building without feature `tls`) and then sending a packet using nmap:
cd examples
cargo run --bin helloworld-server …

Prevent server from exiting on ECONNABORTED

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/server/mod.rs

Signed-off-by: Bugen Zhao <i@bugenzhao.com>
This is basically the dual of #1835 on the server side. Can refer to the motivation of #1835.
Add the configuration for the server with the same interface as the client (transport). Also refine the documentation.

server: allow setting max_header_list_size

---

tests/integration_tests/tests/connection.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/tls.rs

The recent breaking change in https://github.com/hyperium/tonic/pull/1731 removed the ability for generated client functions to connect to HTTPS endpoints through strings alone.
For example the doctest below  would fail in 0.12.x `tonic-build` connection code:
https://github.com/hyperium/tonic/blob/03913b987ea75ac6902799f0cfa36b583b5d40e1/tonic/src/transport/channel/endpoint.rs#L79-L82
This PR introduces a best attempt at picking up tls feature flags in `Endpoint::new` to allow successfully connecting to strings that contain `https://` once more

fix(tonic-build,tonic) Add back TLS handling in genereated `Client::connect` code

---

tonic-web/src/call.rs

…
Attempting to parse a real grpc-web message response from an envoy server that added a few other trailers resulted in a panic
Root issue was a simple failure to advance the cursor in a buffer read. It happened to work for the first trailer so this wasn't already caught in tests

fix(tonic-web): fix panic caused in trailer parsing when there is more than one trailer

---

tonic-web/src/call.rs

Attempting to parse a grpc response from an envoy proxy that inserts trailers causes an infinite loop
Digging in to the code I found that there was an attempt to read more data after parsing trailers but the buffer was empty, ending up in the same place again. Guarding this fixes the issue and I can successfully fetch a message.
Note this fix needs to be combined with #1880 to get a valid grpc response back (otherwise it panics earlier).

fix(web): fix empty trailer parsing causing infinite parser loop

---

tonic/src/transport/server/incoming.rs

Share error handling logic from #1874 between TCP and TLS accept loops.
cc @grembo

server: unify accept error handling

---

examples/src/h2c/server.rs
examples/src/tls_rustls/server.rs

Calls `Routes::prepare` in examples.

chore(examples): Call Routes::prepare

---

examples/src/reflection/server.rs
tonic-reflection/src/server/mod.rs
tonic-reflection/src/server/v1.rs
tonic-reflection/src/server/v1alpha.rs
tonic-reflection/tests/server.rs
tonic-reflection/tests/versions.rs

In tonic 0.12, we [upgraded to v1 reflection](https://github.com/hyperium/tonic/pull/1701). However, some tools (like Postman and Kreya) still use the v1alpha1 version of the reflection schema. This PR tries to add back the v1alpha reflection schema with minimal code duplication, by moving code around so that the `Builder` builds a schema-independent `ReflectionServiceState` which can be wrapped in a server following the requested schema version.
This should supersede #1787 and #1822 (thanks @ttkjesper for the input -- I've stolen your tests) while reducing code duplication.
Would be happy to get feedback on whether this works for people affected by this issue, as I'd like to get this merged into the [pending 0.12.2](https://github.com/hyperium/tonic/pull/1881) release.

tonic-reflection: add back support for v1alpha reflection protocol

---

tonic/src/service/router.rs

Allows unreachable patterns for empty type. This will warn from Rust 1.82.
https://github.com/rust-lang/rust/pull/122792

chore(router): Allow unreachable patterns

---

CHANGELOG.md
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

Prepare release for #1866, which fixes a regression from #1731.
Would like to get this merged before releasing:

chore: prepare 0.12.2 release

---

Cargo.toml
tests/deprecated_methods/Cargo.toml
tests/deprecated_methods/build.rs
tests/deprecated_methods/proto/test.proto
tests/deprecated_methods/src/lib.rs
tests/deprecated_methods/tests/deprecated_methods.rs
tonic-build/src/client.rs
tonic-build/src/lib.rs
tonic-build/src/manual.rs
tonic-build/src/prost.rs

When an rpc method is marked as deprecated, tonic currently doesn't forward it to the user (#1512).
This PR adds the `#[deprecated]` attribute to generated rust client methods that are marked as deprecated in a protobuf file. I've added `Method::deprecated` which returns if the method is deprecated and is checked when the client code is generated. ~~I'd consider this a breaking change, as the `Method` trait is publicly exposed and the code will now emit warnings if a deprecated generated method is called.~~ `Method::deprecated` has a default implementation which always returns `false`.

feat(build): Add `#[deprecated]` to deprecated client methods

---

interop/src/server.rs

Uses ordinary path to `Result`, and uses it as `StdResult` instead of its full path.

chore(interop): Refactor path to Result

---

tonic/src/transport/server/mod.rs

See:
- https://github.com/hyperium/tonic/issues/1428
- https://github.com/hyperium/hyper/pull/3729
Added a new configuration parameter: max_connection_age_ms.
Example:
Server::builder()
.max_connection_age_ms(5)
.add_service(GreeterServer::new(greeter))
.serve(addr)
.await?;
I'm using max_connection_age_ms set to 5 ms only for test purposes. In production it should be set to a greater value.
See:
- https://github.com/ionut-slaveanu/tonic/tree/master/examples/src/max_connection_age
We try to gracefully close each connection to the server after max_connection_age_ms milliseconds have passed.
Run:
./target/release/max-connection-age-server as grpc server.
As a client, i'm using ghz: 
- https://ghz.sh/ 
Example of generating requests with:
./ghz --insecure   --proto …

Added support for grpc max_connection_age_ms

---

interop/build.rs
tonic-build/src/prost.rs
tonic-web/tests/integration/build.rs

Reverts #1821.
Resolves #1894.

Revert "fix(tonic-build): cargo build script outputs are not functional"

---

Cargo.toml
tests/skip_debug/Cargo.toml
tests/skip_debug/build.rs
tests/skip_debug/proto/test.proto
tests/skip_debug/src/lib.rs
tests/skip_debug/tests/skip_debug.rs
tonic-build/src/prost.rs

[skip_debug](https://docs.rs/prost-build/0.13.1/prost_build/struct.Config.html#method.skip_debug) is a method supported for prost `Config`. tonic doesn't support this method today.
Added a new `skip_debug()` method to prost `Builder` and added a corresponding test.

feat: plumb skip_debug through prost builder

---

tonic/src/transport/server/incoming.rs

As discussed in https://github.com/hyperium/tonic/pull/1882#issuecomment-2302371292.
cc @grembo

server: ignore more error kinds in incoming socket stream

---

.gitignore

Very minor quality-of-life thing; I keep accidentally committing the dir that IDEA creates and having to remove it.

chore(Dev): ignore .idea directory that Intellij IDEs add automatically

---

.github/workflows/CI.yml
README.md

I intend to increase the MSRV of `prost` to 1.71.1, because of their dependencies. I intend to release that in 0.13.3 (current version is 0.13.1). https://github.com/tokio-rs/prost/pull/1135
I think `tonic` should already increase to prevent future breakage.

chore: Bump msrv to 1.71.1

---

tonic/src/codec/compression.rs
tonic/src/codec/decode.rs
tonic/src/codec/encode.rs
tonic/src/codec/mod.rs

I want to create a middleware grpc service that can listen to regular grpc calls, and forward them to another service as grpc-web calls. In order to do this fully generically, there needs to be made public some internals of tonic that are normally called via the `Grpc` service that the generated service code uses.
Publish the minimal set of symbols that are required
---
If there is interest, I can create a new example in the examples dir to demonstrate grpc-web proxying. I've only tested unary calls locally so far.

feat(grpc-web): make public some methods to enable grpc-web client proxying

---

.github/workflows/CI.yml
CONTRIBUTING.md

Removes unnecessary `protoc` version lock. This allows to check with the latest version of `protoc`.

chore(ci): Remove unnecessary protoc version lock

---

tonic/Cargo.toml
tonic/src/transport/channel/service/tls.rs
tonic/src/transport/service/tls.rs

Updates to `rustls-native-certs` 0.8.

chore(tls): Update to rustls-native-certs 0.8

---

codegen/src/main.rs
examples/build.rs
tests/default_stubs/build.rs
tests/disable_comments/build.rs
tests/extern_path/my_application/build.rs
tests/root-crate-path/build.rs
tests/skip_debug/build.rs
tests/use_arc_self/build.rs
tests/wellknown-compiled/build.rs
tonic-build/src/prost.rs
tonic-web/tests/integration/build.rs

Renames `compile()` method with `compile_protos()` and `compile_with_config` with `compile_protos_with_config`. This makes the same naming rule with the API compiling from file descriptor set, and also makes it easier to understand as it has the same naming style as `prost-build`.

feat(build): Rename compile method with compile_protos

---

tonic-build/src/lib.rs
tonic-build/src/prost.rs

Adds a simple API to compile file descriptor set, corresponding to `tonic_build::compile_protos()`.

feat(build): Add simple api to compile file descriptor set

---

examples/routeguide-tutorial.md
tonic-build/README.md
tonic-build/src/lib.rs
tonic/src/macros.rs

Replaces deprecated `compile` with `compile_protos`.

chore(doc): Replace deprecated compile with compile_protos

---

tonic/src/transport/channel/tls.rs

The sentences like "Sets the CA Certificate" are possibly read as overwriting the existing config.

chore(doc): Update document to add ca certificate

---

.github/workflows/CI.yml

Adds `clippy` job to check only error to detect some kind of error like #1908 which is difficult to find.

chore(ci): Add clippy job to check error

---

tests/skip_debug/Cargo.toml
tests/skip_debug/build.rs
tests/skip_debug/src/lib.rs

chore(test): Refactor skip debug test

---

tonic-build/src/prost.rs

Adds document about how `prost-build`'s config is used.

chore(doc): Add document about how prost-build config is used

---

tonic-build/src/server.rs
tonic-health/src/generated/grpc_health_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1alpha.rs

Resolves #1172. In this case, `unwrap` can be removed.

chore(build): Remove unwrap from generated code

---

tonic/src/macros.rs

Method `format` was removed in #904, but this doc was not updated because it has an attribute `ignore`.

Update docs in tonic::macros

---

tonic-build/src/client.rs
tonic-build/src/server.rs
tonic-health/src/generated/grpc_health_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1.rs
tonic-reflection/src/generated/grpc_reflection_v1alpha.rs

The `clippy::wildcard_imports` is not enabled by default, but some projects might enable it, causing tonic-build to generate code failing to lint.
`#[allow(clippy::wildcard_imports)]` in generated code

build: suppress `clippy::wildcard_imports` in generated code

---

tonic/src/transport/server/incoming.rs

When receiving non TLS packets (like TCP healtchecks), the server shuts down due to the UnexpectedEof returned by rustls.
Ignore this error

fix(tls): do not shutdown server on unexpected Eof

---

tonic-build/src/lib.rs

Reexports types which are used with builder based on `prost`.

feat(build): Reexport types related to prost

---

tonic/src/transport/server/incoming.rs

This is a continuation of #1938. Other errors are not fatal to the server as a whole.
I observed this today in production (we are already running #1938). While connections breaking are much less rare than "unexpected eof", they still happened once:
```
Sep 19 14:56:13 api01 watchdog.sh[19879]: {"timestamp":"2024-09-19T14:56:13.360774Z","level":"DEBUG","message":"accept loop error","error":"Connection reset by peer (os error 104)","target":"tonic::transport::server::incoming"}
```
The solution is to add "connection reset" and "broken pipe" errors to the list of non-fatal errors that make the accept loop continue.

fix(tls): do not shutdown server on broken connections

---

tonic/Cargo.toml

The `channel` feature needs `tower?/util` feature to be built with `no-default-features`.

fix: add `tower?/util` dep for `channel` feature only builds

---

tonic/Cargo.toml
tonic/src/client/grpc.rs
tonic/src/codec/encode.rs
tonic/src/codec/mod.rs
tonic/src/codec/prost.rs
tonic/src/server/grpc.rs

Follow-up to #1884 to simplify the newly public low-level `EncodeBody` API.
cc @zakhenry

Clean up EncodeBody API

---

tonic-web/src/layer.rs
tonic-web/src/lib.rs
tonic-web/src/service.rs

Removes unnecessary `BoxError` type alias and `Into<BoxError>` trait bound.

chore(web): Remove unnecessary BoxError type alias and Into BoxError trait bound

---

tonic-web/src/layer.rs
tonic-web/src/lib.rs

Removes `Clone`, `Send` and static lifetime bound from service.

chore(web): Remove Clone Send and static lifetime bound from service

---

tonic/src/transport/service/grpc_timeout.rs

`let-else` can be used to flatten this implementation.

chore(server): Use let-else statement

---

tonic/src/service/router.rs

Given `S: Service<Request<BoxBody>, Response = Response<BoxBody>, Error = Infallible>`, 
`S::Error: Into<crate::Error> + Send` is redundant

chore: redundant constraint on error type required to be `Infallible`

---

tonic/src/service/router.rs

Adds a method to get mutable reference to `axum::Router`.

feat(router): Add method to get mutable reference to axum::Router

---

tonic/src/transport/server/incoming.rs

Related to https://github.com/hyperium/tonic/pull/1948 and https://github.com/hyperium/tonic/pull/1938
We have a tls server in production and we started seeing instances of the server exiting due to errors in the accept loop after upgrading to version 0.12.2.
We pinned our tonic version to commit sha 474390bdd06ca3f0be007250b1afbfec6a655873 and that fixed most of the issues. However we still see shutdowns on connection timeout errors.
```
2024-10-04T14:01:51.137261894+00:00 - DEBUG tonic::transport::server::incoming - accept loop error error=Connection timed out (os error 110)
```
Add `io::ErrorKind::TimedOut` to the list of errors to ignore

fix(tls): do not shutdown the server on connection timeout errors

---

tonic/src/service/interceptor.rs
tonic/src/status.rs

We have middleware that works for both gRPC and non-gRPC requests where it would be useful to leverage `Status::into_http()` in case the request content-type indicates it was a gRPC request, but don't want to couple to tonic's `BoxBody`.
For creating an empty body, relying on `Default` seems pretty reasonable and is an existing pattern in the ecosystem e.g. https://github.com/tower-rs/tower-http/blob/66dd321a73f87ab204011f07853e156f81cfeb7b/tower-http/src/timeout/service.rs#L109
Make `into_http` generic over the body so long as it implements `Default`.

Make `Status::into_http()` generic over any kind of `Default`-able Body

---

tonic-web/src/lib.rs
tonic-web/src/service.rs

feat(web): Remove enable api

---

tonic-web/src/layer.rs

Removes the unnecessary bound from `GrpcWebLayer`.

chore(web): Remove unnecessary bound from GrpcWebLayer

---

tonic/src/service/interceptor.rs

Removes unnecessary `BoxBody` from interceptor.

chore(interceptor): Remove unnecessary BoxBody from interceptor

---

tonic-web/src/call.rs

`Error` trait seems not to be needed.

chore(web): Relax GrpcWebCall error bound

---

tonic/Cargo.toml
tonic/src/service/router.rs

Removes unnecessary `BoxBody` from router's response body.

feat(router): Remove unnecessary BoxBody from response body

---

tonic-web/src/client.rs

Removes unnecessary bound from `GrpcWebClientService`.

chore(web): Remove unnecessary bound from GrpcWebClientService

---

tonic/src/transport/channel/endpoint.rs

Add getters for tcp settings to Endpoints. The purpose for this is that `connect_with_connector` doesn't set TCP settings on the socket, because it's using a provided connector. In the cases where a library is creating a custom TCP connection, we want to be able to respect user tcp settings, in particular connection timeout. Adding these getters allows this.
The purpose for this is that `connect_with_connector` doesn't set TCP settings on the socket, because it's using a provided connector. In the cases where a library is creating a custom TCP connection, we want to be able to respect user tcp settings, in particular connection timeout. Adding these getters allows this.
Adds simple getters for existing tcp settings on an endpoint.

feat: Add tcp setting getters to endpoint

---

tonic/src/service/interceptor.rs

Renames f with interceptor to represent what it is more descriptive.

chore(interceptor): Rename f with interceptor

---

tonic/src/service/router.rs

Relaxes service body type for `Routes`.

chore(router): Relax service body type for routes

---

tonic/src/transport/server/incoming.rs

https://github.com/hyperium/tonic/issues/1989
A [previous commit](https://github.com/hyperium/tonic/commit/c3be20c86e1a6dfa3523b2d77e8c503d0f5b2ce3) altered the handling of errors during TLS handshakes. Prior to that change, the various and sundry error IO errors which can arise during a handshake were ignored. The commit in question changed the behavior to instead exit the accept loop (and thus shut down the server) if any IO error which is not explicitly listed occurs. Since that commit, several error kinds have been added to the list piecemeal to address shutdowns, but the tail of errors which might need to be added is likely long.
This change aims to return the handling of TLS errors to the previous state where all errors from `tls.accept` would be swallowed.
This "de-unifies" the …

server: swallow TLS errors in the accept loop

---

examples/src/tower/client.rs
examples/src/tower/server.rs
tonic/src/service/interceptor.rs
tonic/src/service/mod.rs

Changes `InterceptorLayer` constructor associated function.

feat(interceptor): Change InterceptorLayer constructor associated function

---

examples/Cargo.toml
interop/Cargo.toml
tests/compression/Cargo.toml
tests/integration_tests/Cargo.toml
tonic-web/Cargo.toml
tonic/Cargo.toml
tonic/src/transport/channel/mod.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/server/service/io.rs

chore: Update to tower 0.5

---

tonic/src/body.rs
tonic/src/client/grpc.rs
tonic/src/client/service.rs
tonic/src/codec/decode.rs
tonic/src/lib.rs
tonic/src/server/grpc.rs
tonic/src/service/router.rs
tonic/src/status.rs
tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/mod.rs
tonic/src/transport/channel/service/add_origin.rs
tonic/src/transport/channel/service/connection.rs
tonic/src/transport/channel/service/connector.rs
tonic/src/transport/channel/service/discover.rs
tonic/src/transport/channel/service/reconnect.rs
tonic/src/transport/channel/service/tls.rs
tonic/src/transport/channel/tls.rs
tonic/src/transport/error.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/server/service/recover_error.rs
tonic/src/transport/server/service/tls.rs
tonic/src/transport/server/tls.rs
tonic/src/transport/service/grpc_timeout.rs
tonic/src/transport/service/tls.rs

Renames `Error` to `BoxError` to describe what it is more descriptive. Given that there is other `Error` type, I feel it is clearer.

chore: Rename Error to BoxError

---

tonic-build/Cargo.toml
tonic-build/src/lib.rs

Makes cleanup-markdown feature additive.

feat(build): Make cleanup-markdown feature additive

---

tonic/src/transport/channel/mod.rs

The connector is required to be a `Service` that accepts a `http::Uri` and returns a connection implementing hyper's IO traits, which is a very reasonable requirement that can be fulfilled by advanced users that need to customize any mechanics that don't fit into the paved path for HTTP and HTTPS with tonic.
One such requirement is customizing `rustls::ClientConfig`, which has come up for a number of users. They have been pointed in the direction of a custom connector, but the APIs on `Endpoint` are not always suitable:
`Endpoint::connect_(lazy_)with_connector` always wraps the provided connector with `transport::channel::service::Connector`. This wrapper raises an error `HttpsUriWithoutTlsSupport` if (the scheme is `https://` + the `tls` feature is enabled + and `Endpoint::tls_config()` …

feat: make pub `Channel` fns that allow creating it from a custom connector

---

tonic/src/body.rs

Avoids duplicate box on constructing `BoxBody`.

chore: Avoid duplicate box on constructing BoxBody

---

.github/workflows/CI.yml

This seems to be introduced at the recent changes in `pin-project`.
https://github.com/taiki-e/pin-project/pull/357

chore: Update to cargo-check-external-types 0.1.13

---

deny.toml

Replaces `name` field with `crate` in the cargo-deny config as it is an old format.
https://embarkstudios.github.io/cargo-deny/checks/cfg.html?highlight=name#old-format

chore: Replace name field with crate in cargo-deny config

---

tonic/src/transport/channel/service/tls.rs
tonic/src/transport/server/service/tls.rs
tonic/src/transport/service/tls.rs

Refactors parsing certificate and identity.

chore(tls): Refactor parsing certificate and identity

---

deny.toml

Adds `itertools` 0.12.1 to cargo-deny skip config.

chore: Add itertools 0.12.1 to cargo-deny skip config

---

examples/Cargo.toml
examples/src/tls_rustls/client.rs
examples/src/tls_rustls/server.rs
tonic/Cargo.toml
tonic/src/transport/service/tls.rs

Uses `rustls-pki-types` pem APIs directly. Depends on  #1763.

chore(tls): Use rustls-pki-types pem api

---

tonic/src/transport/server/mod.rs

Removes `into_service()` api. This is the same as the one composed of the layers and the `Routes`.

feat(server): Remove into_service api

---

tonic/src/transport/channel/service/tls.rs

Tonic hard codes the `ring` feature in rustls. When another crate depends on default rustls features they will additionally have the `aws-lc-rs` feature enabled in rustls. Having both
of these features enabled makes rustls not work "out of the box" as there will no longer
be a default crypto provider.
Make tonic use the ring provider as a fallback if no default provider is found.

use ring if no default crypto provider is found

---

tonic/src/transport/server/service/recover_error.rs

Removes unnecessary bound from `MaybeEmptyBody`.

chore(server): Remove unnecessary bound from MaybeEmptyBody

---

tonic-web/src/lib.rs
tonic-web/src/service.rs

Relaxes `GrpcWebService`'s request body type.

feat(web): Relax GrpcWebService request body type

---

deny.toml

Updates to Unicode-3.0 license.
https://github.com/dtolnay/unicode-ident/releases/tag/1.0.14

chore: Update cargo-deny config to allow Unicode-3.0 license

---

tests/integration_tests/tests/client_layer.rs
tests/integration_tests/tests/complex_tower_middleware.rs
tests/integration_tests/tests/connect_info.rs
tests/integration_tests/tests/connection.rs
tests/integration_tests/tests/extensions.rs
tests/integration_tests/tests/http2_keep_alive.rs
tests/integration_tests/tests/interceptor.rs
tests/integration_tests/tests/origin.rs
tests/integration_tests/tests/routes_builder.rs
tests/integration_tests/tests/status.rs
tests/integration_tests/tests/streams.rs
tests/integration_tests/tests/user_agent.rs

Uses any port in the tests to allow parallel tests.

chore(test): Use any port in test

---

tests/root-crate-path/src/main.rs
tonic/src/transport/server/mod.rs

Removes outdated clippy configs.

chore: Remove outdated clippy config

---

examples/src/streaming/server.rs

Removes a redundant pattern match.

chore(examples): Remove redundant pattern match

---

tests/integration_tests/tests/client_layer.rs
tests/integration_tests/tests/connect_info.rs
tests/integration_tests/tests/connection.rs
tests/integration_tests/tests/extensions.rs
tests/integration_tests/tests/http2_keep_alive.rs
tests/integration_tests/tests/http2_max_header_list_size.rs
tests/integration_tests/tests/interceptor.rs
tests/integration_tests/tests/origin.rs
tests/integration_tests/tests/routes_builder.rs
tests/integration_tests/tests/status.rs
tests/integration_tests/tests/user_agent.rs
tonic/src/transport/server/incoming.rs
tonic/src/transport/server/mod.rs

chore(server): Refactor TcpIncoming

---

tonic-reflection/Cargo.toml
tonic-reflection/src/server/v1.rs
tonic-reflection/src/server/v1alpha.rs

Exposes `ReflectionService` to allow users to use the type of reflection services.

feat(reflection): Expose ReflectionService

---

tonic-web/src/client.rs
tonic-web/src/service.rs

Implements `Debug` for `ResponseFuture`s.

feat(web): Implement Debug for ResponseFuture

---

examples/routeguide-tutorial.md
examples/src/routeguide/client.rs

1. The following logs line prints a feature but the logs mentions `NOTE`. `NOTE` messages are printed later in bidirectional stream code, so this may be a copy/paste error.
```rust
println!("NOTE = {:?}", feature);
```
2. The following line in the markdown file declares `tx` as `mut` which and detected by `rust-analyzer`. The actual client file doesn't declare `tx` as `mut`.
```rust
let (mut tx, rx) = mpsc::channel(4);
```
Client code:
https://github.com/hyperium/tonic/blob/a7030a7fb7f5e2b270fb47c3f9701a798d81513f/examples/src/routeguide/server.rs#L47-L48
1. Make the print statement accurate.
2. Remove the unnecessary `mut`.

examples: Minor fix in routeguide example

---

.github/workflows/CI.yml

Updates to nightly-2024-12-01 on udeps ci.

chore(ci): Update to nightly-2024-12-01 on udeps ci

---

tonic/src/service/interceptor.rs
tonic/src/transport/server/mod.rs

Adds response body for interceptor.

chore(interceptor): Add response body for interceptor

---

.github/workflows/CI.yml

Uses cargo-deny directly. This avoids building container images.

chore(ci): Use cargo-deny directly

---

tonic/Cargo.toml
tonic/src/transport/server/io_stream.rs
tonic/src/transport/server/mod.rs

Adds `ServerIoStream` type to represent the server io stream.

chore(server): Add ServerIoStream type

---

deny.toml

Resolved at `tower` 0.5.2.
https://github.com/tower-rs/tower/releases/tag/tower-0.5.2

chore: Remove sync_wrapper 0.1.2 from cargo-deny skip config

---

examples/Cargo.toml
tonic/Cargo.toml

`tokio-rustls` 0.16.1 has been released, which ensures that the `rustls` version is 0.23.15, which uses `rustls-pki-types` 0.10, which introduced PEM APIs and the Error trait is implemented on the error type.
https://crates.io/crates/tokio-rustls/0.26.1

chore: Update to tokio-rustls 0.16.1 and remove rustls-pki-types from direct dependency

---

tonic/src/transport/server/service/recover_error.rs

Converting from the `Status` to http response should be done with `Status::into_http` which is implemented for that purpose.
Resolves #2092.

fix(server): Use Status::into_http api in recover error service

---

tonic/src/codec/compression.rs

Resolves unused import warning without compression features.

chore(test): Resolve unused import warning without compression feature

---

deny.toml

Add `unicode-width` 0.1.14 to cargo-deny skip config

chore: Add unicode-width 0.1.14 to cargo-deny skip config

---

deny.toml

Removes Zlib from cargo-deny config.

chore: Remove Zlib from cargo-deny config

---

.github/workflows/CI.yml
README.md

`axum` 0.8 requires Rust 1.75.
https://github.com/tokio-rs/axum/releases/tag/axum-v0.8.0

chore: Bump msrv to 1.75

---

codegen/Cargo.toml
examples/Cargo.toml
interop/Cargo.toml
tests/ambiguous_methods/Cargo.toml
tests/compression/Cargo.toml
tests/default_stubs/Cargo.toml
tests/deprecated_methods/Cargo.toml
tests/disable_comments/Cargo.toml
tests/extern_path/my_application/Cargo.toml
tests/extern_path/uuid/Cargo.toml
tests/included_service/Cargo.toml
tests/integration_tests/Cargo.toml
tests/root-crate-path/Cargo.toml
tests/same_name/Cargo.toml
tests/service_named_result/Cargo.toml
tests/service_named_service/Cargo.toml
tests/skip_debug/Cargo.toml
tests/stream_conflict/Cargo.toml
tests/use_arc_self/Cargo.toml
tests/web/Cargo.toml
tests/wellknown-compiled/Cargo.toml
tests/wellknown/Cargo.toml

Rust 1.75 supports the manifest without the version field. This regards it as publish false.
https://github.com/rust-lang/cargo/pull/12786/

chore: Remove version and publish field from internal crate

---

Cargo.toml
tonic-build/Cargo.toml
tonic-build/src/lib.rs
tonic-health/Cargo.toml
tonic-health/src/lib.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/lib.rs
tonic-reflection/tests/server.rs
tonic-reflection/tests/versions.rs
tonic-types/Cargo.toml
tonic-types/src/lib.rs
tonic-web/Cargo.toml
tonic-web/src/client.rs
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/benches/decode.rs
tonic/src/lib.rs

Rust 1.74 supports lint config in the manifest.
https://github.com/rust-lang/cargo/pull/12648/

chore: Use lint config in manifest

---

tonic/src/transport/channel/endpoint.rs
tonic/src/transport/channel/service/discover.rs

Adds a helper to create http connector.

chore(channel): Add helper to create http connector

---

README.md

Migrates the readme tutorial section to examples and interop explanation.

chore(doc): Migrate readme tutorial section to examples and interop explanation

---

tonic-health/Cargo.toml
tonic-health/src/server.rs
tonic-reflection/Cargo.toml
tonic-reflection/src/server/v1.rs
tonic-reflection/src/server/v1alpha.rs

Removes unnecessary pin-project.

chore: Remove unnecessary pin-project

---

tonic/src/transport/server/unix.rs

Removes the unnecessary link definition.

chore(doc): Remove unnecessary link definition

---

tonic/src/transport/channel/endpoint.rs

I need to be able to set the local address of a Channel. This is the source IP address the Channel will be coming from. Currently Tonic's Channel builder doesn't expose a way to do this.
Add `local_address` to Endpoint builder.

feat(channel): Add local_address as an option Endpoint builder

---

tonic-reflection/src/server/v1.rs
tonic-reflection/src/server/v1alpha.rs

Refactors ServerReflectionInfoStream.

chore(reflection): Refactor ServerReflectionInfoStream

---

.github/workflows/CI.yml

The doc test does not seem to be needed to be run on each OS.

chore(ci): Run doc test only on ubuntu

---

tonic/src/transport/server/mod.rs

Removes the unnecessary static lifetime bound.

chore(server): Remove unnecessary static lifetime bound

---

tonic-web/src/call.rs

This was reported to me here: https://github.com/sudorandom/fauxrpc/issues/15.
According to the gRPC Web spec, trailers should have a space after the colon, like this:
```http
grpc-status: 0
grpc-message: Message Here
```
But tonic-web client and server both omit the space, like:
```http
grpc-status:0
grpc-message:Message Here
```
This is likely fine for the server to do since most clients can handle having the space or not but the tonic-web client **should** handle the space character being there (or not), which is what this change does.
The solution is to trim a space character from the trailer value, if it exists so that both formats are supported using the tonic-web client.
I am extremely new to rust, so feel free to close this PR or modify it in favor of a more conventionally rusty …

fix(client): improve gRPC-Web client behavior with trailers with a space after the colon

---

tonic/src/metadata/map.rs
tonic/src/status.rs

I got an unexpected JavaScript client-side gRPC-Web error `Uncaught URIError: malformed URI sequence` and traced it down to the `%` character not being encoded by the tonic-based server. My error message included a percent sign 😏.
Correct usage of the dependent crate's `AsciiSet` structure. Otherwise, the `%` character doesn't get changed at all.

Fix percent-encoding of percent sign in `grpc-message` header

---

tonic-web/src/call.rs

Removes byte char slices which is suggested by clippy.

chore(web): Remove byte char slice

---

.github/workflows/CI.yml
Cargo.toml
tonic-build/Cargo.toml
tonic-health/Cargo.toml
tonic-reflection/Cargo.toml
tonic-types/Cargo.toml
tonic-web/Cargo.toml
tonic/Cargo.toml

Introduces rust-version in the manifest. This allows to use MSRV aware dependency resolver.

chore: Introduce rust-version in manifest

---

tonic/src/service/mod.rs
tonic/src/service/recover_error.rs
tonic/src/transport/server/mod.rs
tonic/src/transport/server/service/mod.rs

Exposes the recover error service. This allows it to provide functionality independently of the transport server feature.

feat: Expose recover error service

---

tonic/src/metadata/map.rs

Signed-off-by: hr567 <hr567@hr567.me>
Avoid taking ownership or clone when a HeaderMap reference is needed by adding an AsRef trait.
Add AsRef and AsMut implement

feat(metadata): Implement AsRef and AsMut traits for MetadataMap

---

interop/src/lib.rs

`repeat_n` can be used instead of `repeat` and `take`.

chore(interop): Replace repeat and take with repeat_n

---

tonic/src/transport/service/grpc_timeout.rs

Updates the url to the http crate document.

chore(transport): Update url to http crate document

---

tonic/src/transport/service/grpc_timeout.rs

Removes the redundant type reconstruct.

chore(transport): Remove redundant type reconstruct

---

tonic/src/transport/channel/service/tls.rs
tonic/src/transport/channel/tls.rs
tonic/src/transport/server/service/tls.rs
tonic/src/transport/server/tls.rs

Using `SSLKEYLOGFILE` is helpful when you want to intercept TLS traffic for debugging and is generally supported by many libraries and browsers. Also see: https://wiki.wireshark.org/TLS#using-the-pre-master-secret
Add a `use_key_log` option to server and client TLS configs that -- when set -- will enable rustls's `SSLKEYLOGFILE` handling.

feat: optional `SSLKEYLOGFILE` support

---

prepare-release.sh
tonic-build/src/lib.rs
tonic-health/src/lib.rs
tonic-reflection/src/lib.rs
tonic-types/src/lib.rs
tonic-web/src/lib.rs
tonic/Cargo.toml
tonic/src/lib.rs

Removes `html_root_url`. See https://github.com/tokio-rs/tokio/pull/3489.

chore: Remove html_root_url

---

tonic-web/src/call.rs
tonic-web/src/service.rs
tonic/src/transport/server/io_stream.rs

chore: Remove unused mutability

---

tonic/Cargo.toml

Separated out the change from #2163. This can be applied independently.

feat(tonic): Exclude benches-disabled to remove Apache-2.0 resource

---

tests/ambiguous_methods/src/lib.rs

Removes the unnecessary macro_use.

chore(test): Remove unnecessary macro_use

---

tonic/src/service/router.rs

Uses infallible as the error type directly.

feat(router): Use infallible as error type

---

tonic/src/transport/server/mod.rs

Refactors the default http2 keepalive timeout config.

chore(server): Refactor default http2 keepalive timeout config

---

tonic-reflection/Cargo.toml
tonic/Cargo.toml

This config is set as default.
https://docs.rs/about/builds#detecting-docsrs

chore: Remove unnecessary docs.rs config

---

deny.toml

Removes the resolved cargo-deny config.

chore: Remove resolved cargo-deny config

---

Cargo.toml
grpc/Cargo.toml
grpc/LICENSE
grpc/NOTICE.txt
grpc/src/attributes.rs
grpc/src/client/load_balancing/child_manager.rs
grpc/src/client/load_balancing/mod.rs
grpc/src/client/mod.rs
grpc/src/client/name_resolution/mod.rs
grpc/src/client/service.rs
grpc/src/client/service_config.rs
grpc/src/lib.rs

This PR creates the rough layout for the upcoming grpc crate and license notices.  The biggest notable piece of API is the `load_balancing` package, and it includes a nearly-complete `ChildManager` implementation to show its usage.  Non-LB types that are included are important for the LB API, but left as TODO.
cc @easwars @arjan-bal

Create place for grpc crate and initial contents

---

tonic/src/service/router.rs

Removes unnecessary type converting.

chore(router): Remove unnecessary type converting

---

.github/workflows/CI.yml

Updates to nightly-2025-03-27 on udeps ci.

chore(ci): Update to nightly-2025-03-27 on udeps ci

---

tonic/src/transport/server/mod.rs

This service can be `call`ed immediately because its `poll_ready` is guaranteed to always return `Ready(Ok())`.

chore(server): Remove unnecessary await service ready

---

tonic-health/src/server.rs

We'd like to use tonic-health however we can't currently due to our usage of boxing. I'd like to publicly expose the creation of both HealthReporter and HealthService so we can create our own instances.
health_reporter() function returns `HealthServer<impl Health>` which means it can't be boxed due to the `impl Health`. 
Instead of changing existing API, we can just publicly expose the creation functions, and then use `HealthServer<HealthService>` directly.

feat: expose creation of HealthService and HealthReporter

---

prepare-release.sh
tonic-build/Cargo.toml
tonic-health/Cargo.toml
tonic-reflection/Cargo.toml
tonic-types/Cargo.toml
tonic-web/Cargo.toml
tonic/Cargo.toml

Revert "chore: Prepare `v0.13.1` release"

---

tonic/src/status.rs

chore: box Status contents (#2253)

---

tests/default_stubs/Cargo.toml
tests/default_stubs/tests/default.rs

Uses tempfile crate to handle the temporary file.

chore(test): Use tempfile crate to handle temporary file

---

tonic-build/src/lib.rs
tonic-build/src/server.rs
tonic-prost-build/src/lib.rs

Related to #2341 
Currently, tonic-build generates service traits without any ability to attach additional attributes or proc-macros.
This creates friction when integrating generated traits with tools and frameworks that rely on such attributes.
For example, when using mockall for testing, one cannot simply write:
```rust
#[mockall::automock]
pub trait MyService { ... }
```
because the trait is auto-generated and cannot be easily modified.
As a result, mocking requires duplicating the entire trait or writing manual boilerplate, which is error-prone and difficult to maintain.
This PR adds a new `trait_attribute` configuration method to `tonic-build`, allowing custom attributes (including proc-macros) to be injected into generated service traits.
Example usage:
```rust …
```

feat(build): allow to specify trait attributes

---

tonic-prost-build/src/lib.rs

Tonic v0.13 had [a `service_generator` method on `tonic_build::Builder`](https://docs.rs/tonic-build/0.13.1/tonic_build/struct.Builder.html#method.service_generator), which allowed retrieving the `prost_build::ServiceGenerator` implementation for more advanced customization. This method was removed in v0.14, but would still be useful to have in `tonic_prost_build`.
This adds back the `service_generator` method to `tonic_prost_build::Builder`. The previous implementation of `service_generator` is [here](https://github.com/hyperium/tonic/blob/v0.13.1/tonic-build/src/prost.rs#L703-L707).
I've also removed the `out_dir` field from the `Builder` struct since this was not used and would require the `service_generator` method definition to differ from v0.13.
I've duplicated the …

feat(prost-build): Add `service_generator` method to `Builder`

---

tonic/src/lib.rs

The `prost` feature toggle was removed in `tonic` v0.14, but it remains in the crate documentation. This Pull Request will remove it.
I want to fix the discrepancy between the documentation and the code.
Removed non-existent prost feature flag from documentation.

chore(tonic): Fix to remove documentation for prost feature flag

---

grpc/Cargo.toml
grpc/src/client/load_balancing/registry.rs
grpc/src/client/transport/registry.rs
grpc/src/inmemory/mod.rs

The standard library provides `LazyLock`.
Replaces `once_cell::sync::Lazy` with `LazyLock`.

chore(grpc): Remove once_cell dependency

---

grpc/Cargo.toml
grpc/examples/inmemory.rs
grpc/examples/multiaddr.rs
grpc/src/service.rs

Removes the direct dependent on futures-core and futures-util crates.

chore(grpc): Remove direct dependent on futures-core and futures-util

---

.github/workflows/CI.yml
Cargo.toml
README.md
grpc/Cargo.toml
tonic/src/codec/compression.rs

Closes #2361 
Relax version of the workspace to 1.75 ~~1.82~~, specify msrv for `grpc` crate as 1.86.
Exclude `grpc` and `tonic-protobuf*` from msrv check. They require a higher msrv and they do not specify `rust-version = { workspace = true }`.
A small code change is used because we cannot rely on automatic lifetime extension of temporaries.
~~Without the `grpc` crate we would need to bump only to 1.79 because of `protobuf-codegen v4.31.1-release`.~~
~~With `grpc` we need 1.82 because of `icu_*` crates.~~
~~We could move grpc to another workspace to avoid bumping the tonic to 1.82, but I don't think is worth it.~~

chore: relax msrv for most crates

---

tonic/src/lib.rs

Fixes that the `aws-lc-rs` link in the `tls-aws-lc` feature document does not work.
Add a link definition to the `aws-lc-rs` crate.

chore(doc): Add link definition to aws-lc-rs crate

---

flake.lock
interop/src/lib.rs

Ref https://github.com/hyperium/tonic/pull/2382

chore(ci): allow mismatched_lifetime_syntaxes for grpc interop tests

---

grpc/src/client/load_balancing/child_manager.rs
grpc/src/client/load_balancing/mod.rs
grpc/src/client/load_balancing/pick_first.rs

Add exit_idle to LbPolicy Trait and Child Manager.
@dfawley @easwars

feat(grpc): add exit_idle to LbPolicy trait

---

grpc/src/client/load_balancing/mod.rs
grpc/src/client/load_balancing/test_utils.rs

This PR adds a couple of utility types that will help with testing LB policies at their API level.
This was originally part of https://github.com/hyperium/tonic/pull/2340, and has been split out here to unblock other LB policy PR reviews.

grpc: add testing utilities for LB policy tests

---

grpc/src/macros.rs

Add include_generated_proto! macro for Codelabs purposes.
@dfawley @easwars @LucioFranco

grpc(feat): add macro for pregenerated code

---

examples/routeguide-tutorial.md

There are no `configure()` or `compile_protos()` methods in `tonic-build`. They only exist in `tonic-prost-build`

change `tonic-build` to `tonic-prost-build` in routeguide-tutorial.md
